import { OnDestroy, OnInit } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { AddonType, SubscriptionInfo, UsageItemType } from '@shared/models/subscription.models';
import { ActivatedRoute } from '@angular/router';
import { AdminService } from '@core/http/admin.service';
import { MatDialog } from '@angular/material/dialog';
import { TranslateService } from '@ngx-translate/core';
import { DateAgoPipe } from '@shared/pipe/date-ago.pipe';
import { ErrorStateMatcher } from '@angular/material/core';
import { FormControl } from '@angular/forms';
import { SystemSetupService } from '@core/http/system-setup.service';
import * as i0 from "@angular/core";
declare enum ManageLicenseState {
    MANAGE = "MANAGE",
    ENTER_KEY = "ENTER_KEY"
}
export declare class LicenseManagementComponent extends PageComponent implements OnInit, OnDestroy {
    private route;
    private adminService;
    private systemSetupService;
    private translate;
    private dateAgoPipe;
    private dialog;
    ManageLicenseState: typeof ManageLicenseState;
    UsageItemType: typeof UsageItemType;
    usageItemTypeTranslationMap: Map<UsageItemType, string>;
    usageAddItemTypeTranslationMap: Map<UsageItemType, string>;
    AddonType: typeof AddonType;
    addonTypeTranslationMap: Map<AddonType, string>;
    pePackOffers: import("@shared/models/subscription.models").PePackOffer[];
    pePackOfferInfoMap: Map<import("@shared/models/subscription.models").PePackOffer, import("@shared/models/subscription.models").PePackOfferInfo>;
    get planWithHue(): boolean;
    get planHueClass(): string;
    get isCeGrant(): boolean;
    manageLicenseState: ManageLicenseState;
    subscriptionInfo: SubscriptionInfo;
    aiEnabled: boolean;
    updatedAgo: string;
    keySendError: boolean;
    keySendNetworkError: boolean;
    keySendErrorMessage: string | null;
    keyInput: string;
    keyError: boolean;
    keyErrorStateMatcher: ErrorStateMatcher;
    licenseError: boolean;
    licenseNetworkError: boolean;
    licenseErrorMessage: string | null;
    submittingKey: boolean;
    subscriptionPreview: SubscriptionInfo;
    newLicenseApplied: boolean;
    private updatedAgoTimer?;
    constructor(route: ActivatedRoute, adminService: AdminService, systemSetupService: SystemSetupService, translate: TranslateService, dateAgoPipe: DateAgoPipe, dialog: MatDialog);
    ngOnInit(): void;
    ngOnDestroy(): void;
    manageSubscription($event: Event): void;
    refreshLicenseInfo($event?: Event): void;
    gotoEnterKey(): void;
    gotoManageLicense(refresh?: boolean): void;
    itemLimitWarn(count: number, max: number): boolean;
    itemLimitCritical(count: number, max: number): boolean;
    itemLimitClass(itemType: UsageItemType, count: number, max: number): string;
    addItems($event: Event, itemType: UsageItemType): void;
    upgradePlanForItems($event: Event, itemType: UsageItemType): void;
    addAddOn($event: Event, addonType: AddonType): void;
    upgradePlanForAddon($event: Event, addonType: AddonType): void;
    pasteKey(): Promise<void>;
    onKeyChange(): void;
    checkKey(control: FormControl): void;
    changeKey(): void;
    enabledAddOnsText(subscription: SubscriptionInfo): string;
    private updateSubscriptionInfo;
    private addDevices;
    private addEdges;
    private addInstances;
    private addAiCredits;
    private addAgents;
    private addEdge;
    private addTrendz;
    private addProfessionalUpgrade;
    private addLicenseItem;
    private upgradePlan;
    private openPortalLinkMaybeShowDialog;
    private refreshAgoTextIfNeeded;
    private refreshAgoText;
    private stopAgoTextTimer;
    private clearKeyErrors;
    private onKeySendError;
    private clearLicenseErrors;
    private onLicenseError;
    static ɵfac: i0.ɵɵFactoryDeclaration<LicenseManagementComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<LicenseManagementComponent, "tb-license-management", never, {}, {}, never, never, false, never>;
}
export {};
