import { OnInit } from '@angular/core';
import { ChatMessage } from '@shared/models/solution-creator.models';
import { AiAssistantPromptExample, ApprovalResult, ChatInfo, ToolExecutionResult } from '@shared/models/ai-chat.models';
import { AiAssistantPanelService } from '@core/services/ai-assistant-panel.service';
import { AiPromptInputComponent } from '@home/components/ai/ai-prompt-input.component';
import { MatButton } from '@angular/material/button';
import * as i0 from "@angular/core";
export interface ChatGroup {
    label: string;
    chats: ChatInfo[];
}
export declare class AiAssistantPanelComponent implements OnInit {
    panelService: AiAssistantPanelService;
    promptInput: AiPromptInputComponent;
    get isOpen(): boolean;
    slideDone: import("@angular/core").WritableSignal<boolean>;
    loading: import("@angular/core").WritableSignal<boolean>;
    isCreatingNew: import("@angular/core").WritableSignal<boolean>;
    messages: import("@angular/core").WritableSignal<ChatMessage[]>;
    completedExecutions: import("@angular/core").WritableSignal<Record<string, ToolExecutionResult>>;
    chatId: import("@angular/core").WritableSignal<string>;
    subTitle: import("@angular/core").Signal<any>;
    activePlaceholder: import("@angular/core").Signal<any>;
    promptExamples: import("@angular/core").Signal<AiAssistantPromptExample[]>;
    autoApprove: import("@angular/core").Signal<boolean>;
    selectedChatTitle: import("@angular/core").Signal<string>;
    groupedChats: import("@angular/core").Signal<ChatGroup[]>;
    private aiChat;
    private dialog;
    private translate;
    private matDialog;
    private store;
    private destroyRef;
    private sanitizer;
    private elementRef;
    private loadChat$;
    private cancelMessage$;
    private sessionAffectedEntities;
    private messageCancelled;
    private openEffect;
    private lastContextKey;
    private contextSwitchEffect;
    ngOnInit(): void;
    close(): void;
    onSlideEnd(event: TransitionEvent): void;
    onApprovalAction(event: ApprovalResult): void;
    setMenuWidth(triggerEl: MatButton): void;
    selectChat(chat: ChatInfo): void;
    useExample(example: AiAssistantPromptExample): void;
    sendMsgFromUser(msg: string): void;
    reset(createNew?: boolean): void;
    private cancelActiveMessage;
    private suspendOnClose;
    private dropChatFromOtherContext;
    renameChat(): void;
    deleteChat(): void;
    private loadChats;
    private selectLastChat;
    private sendMessage;
    private resolveClientContextToSend;
    private handleChatEvent;
    private handleChatTitleGenerated;
    private handleToolApproval;
    private initLoadingState;
    private stopLoadingState;
    private showErrorMessage;
    private showErrorToast;
    static ɵfac: i0.ɵɵFactoryDeclaration<AiAssistantPanelComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AiAssistantPanelComponent, "tb-ai-assistant-panel", never, {}, {}, never, never, false, never>;
}
