import { OnDestroy } from '@angular/core';
import { AiAssistantPanelConfig, AiChatClientContext, AiChatView, ChatInfo } from '@shared/models/ai-chat.models';
import { EntityId } from '@shared/models/id/entity-id';
import * as i0 from "@angular/core";
export declare class AiAssistantPanelService implements OnDestroy {
    private _open;
    readonly open: import("@angular/core").Signal<boolean>;
    private _enabled;
    readonly enabled: import("@angular/core").Signal<boolean>;
    private _config;
    readonly config: import("@angular/core").Signal<AiAssistantPanelConfig>;
    private _detailsOpen;
    readonly detailsOpen: import("@angular/core").Signal<boolean>;
    private _clientContext;
    readonly clientContext: import("@angular/core").Signal<AiChatClientContext>;
    private _sentClientContextByChat;
    private _chats;
    readonly chats: import("@angular/core").Signal<ChatInfo[]>;
    private _lastChatIdByContext;
    private static readonly AUTO_APPROVE_STORAGE_KEY;
    private localStorage;
    private store;
    private destroyRef;
    private _autoApproveUserId;
    private _autoApproveChats;
    private _autoApproveUserSync;
    private _updatedData$;
    readonly updatedData$: import("rxjs").Observable<EntityId[]>;
    private _teardownTimer;
    toggle(): void;
    setChats(chats: ChatInfo[]): void;
    addChat(chat: ChatInfo): void;
    updateChatTitle(chatId: string, title: string): void;
    removeChat(chatId: string): void;
    isAutoApprove(chatId: string | undefined): boolean;
    setAutoApprove(chatId: string, enabled: boolean): void;
    private pruneAutoApproveChats;
    private autoApproveStorageKey;
    private loadAutoApproveChats;
    private persistAutoApproveChats;
    readonly contextKey: import("@angular/core").Signal<string>;
    setLastChatId(id: string | undefined): void;
    lastChatIdForContext(): string | undefined;
    close(): void;
    openPanel(): void;
    setEnabled(enabled: boolean): void;
    setConfig(config: AiAssistantPanelConfig | null): void;
    setDetailsOpen(open: boolean): void;
    setClientContext(ctx: AiChatClientContext | null): void;
    setClientContextForView(view: AiChatView): void;
    getSentClientContext(chatId: string): AiChatClientContext | undefined;
    markClientContextSent(chatId: string, ctx: AiChatClientContext): void;
    ngOnDestroy(): void;
    emitUpdatedData(affectedEntities: Array<EntityId>): void;
    teardown(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AiAssistantPanelService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<AiAssistantPanelService>;
}
