import { DomSanitizer } from '@angular/platform-browser';
import { Store } from '@ngrx/store';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { AppState } from '@core/core.state';
import { EntityService } from '@core/http/entity.service';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import { WidgetContext } from '@home/models/widget-component.models';
import { EntityId } from '@shared/models/id/entity-id';
import { WidgetMobileActionDescriptor } from '@shared/models/widget.models';
import { LiveTrackingConfig, LiveTrackingSaveInfo, MobileLocationResult, SaveBrowserLocationDescriptor } from '@shared/models/location.models';
import { MobileService } from '@core/services/mobile.service';
import * as i0 from "@angular/core";
export declare class LocationService {
    private store;
    private translate;
    private sanitizer;
    private mobileService;
    private entityService;
    private userPermissionsService;
    constructor(store: Store<AppState>, translate: TranslateService, sanitizer: DomSanitizer, mobileService: MobileService, entityService: EntityService, userPermissionsService: UserPermissionsService);
    saveMobileActionLocation(ctx: WidgetContext, mobileAction: WidgetMobileActionDescriptor, locationResult: MobileLocationResult, currentEntityId?: EntityId): Observable<LiveTrackingSaveInfo>;
    saveBrowserLocation(ctx: WidgetContext, config: SaveBrowserLocationDescriptor, currentEntityId?: EntityId): void;
    liveTrackingArgs(ctx: WidgetContext, mobileAction: WidgetMobileActionDescriptor, currentEntityId?: EntityId): Observable<[LiveTrackingConfig] | []>;
    liveTrackingInfo(config: LiveTrackingConfig): LiveTrackingSaveInfo | null;
    private getCurrentPosition;
    private saveErrorMessage;
    private resolveTargetEntity;
    private resolveAttributeSourceEntity;
    private resolveEntityAlias;
    private resolveTargetEntityName;
    private currentUserEntityId;
    private currentDashboardInfo;
    private parseTargetEntityAttributeValue;
    private keyMappings;
    private hasLocationValue;
    private locationValues;
    private saveKeys;
    private requiredWriteOperations;
    private checkWritePermissions;
    static ɵfac: i0.ɵɵFactoryDeclaration<LocationService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<LocationService>;
}
