import { RequestConfig } from './http-utils';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { PageLink } from '@shared/models/page/page-link';
import { PageData } from '@shared/models/page/page-data';
import { EntityId } from '@shared/models/id/entity-id';
import { EntityType } from '@shared/models/entity-type.models';
import { EntityInfoData } from '@shared/models/entity.models';
import { Agent, AgentAppEvent, AgentAppEventActionType, AgentAppEventInfo, AgentAppEventRequest, AgentAppInstallResponse, AgentAppProfile, AgentAppProfileInfo, AgentAppProfileRelationInfo, AgentAppTemplate, AgentAppUnit, AgentApplication, AgentApplicationInfo, AgentApplicationType, AgentBulkAction, AgentBulkActionEventStats, AgentInstructions, AgentProfile, AgentProfileInfo, AgentInfo, BulkOperationPreview, BulkOperationRequest, BulkOperationResult } from '@shared/models/agent.models';
import * as i0 from "@angular/core";
export declare class AgentService {
    private http;
    constructor(http: HttpClient);
    getAgentById(agentId: string, config?: RequestConfig): Observable<Agent>;
    getAgentInfoById(agentId: string, config?: RequestConfig): Observable<AgentInfo>;
    getAgentInfosByIds(agentIds: string[], config?: RequestConfig): Observable<AgentInfo[]>;
    getAgentInstallInstructions(agentId: string, method?: string, config?: RequestConfig): Observable<AgentInstructions>;
    getAgentProvisionInstructions(agentProfileId: string, method?: string, config?: RequestConfig): Observable<AgentInstructions>;
    /**
     * Creates the agent-scoped event that makes the agent replace its own container. Blocks every
     * application event for that agent until it completes.
     */
    upgradeAgent(agentId: string, imageRef: string, config?: RequestConfig): Observable<AgentAppEvent>;
    saveAgent(agent: Agent, entityGroupIds?: string | string[], config?: RequestConfig): Observable<Agent>;
    deleteAgent(agentId: string, config?: RequestConfig): Observable<void>;
    getTenantAgentInfos(pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentInfo>>;
    getCustomerAgentInfos(customerId: string, pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentInfo>>;
    getAgentProfileById(agentProfileId: string, config?: RequestConfig): Observable<AgentProfile>;
    getAgentProfileInfoById(agentProfileId: string, config?: RequestConfig): Observable<AgentProfileInfo>;
    saveAgentProfile(agentProfile: AgentProfile, config?: RequestConfig, appProfileIds?: string[]): Observable<AgentProfile>;
    deleteAgentProfile(agentProfileId: string, config?: RequestConfig): Observable<void>;
    setDefaultAgentProfile(agentProfileId: string, config?: RequestConfig): Observable<AgentProfile>;
    getDefaultAgentProfileInfo(config?: RequestConfig): Observable<AgentProfileInfo>;
    getTenantAgentProfiles(pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentProfile>>;
    getTenantAgentProfileInfos(pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentProfileInfo>>;
    getAgentProfileAppProfileInfos(agentProfileId: string, config?: RequestConfig): Observable<AgentAppProfileRelationInfo[]>;
    assignAppProfileToAgentProfile(agentProfileId: string, applicationProfileId: string, config?: RequestConfig): Observable<void>;
    assignAppProfilesToAgentProfile(agentProfileId: string, appProfileIds: string[], config?: RequestConfig): Observable<void>;
    unassignAppProfileFromAgentProfile(agentProfileId: string, applicationProfileId: string, config?: RequestConfig): Observable<void>;
    setAppProfileRelatesOnAutoDiscovery(agentProfileId: string, applicationProfileId: string, relate: boolean, config?: RequestConfig): Observable<void>;
    previewBulkOperation(agentProfileId: string, applicationProfileId: string, request: BulkOperationRequest, config?: RequestConfig): Observable<BulkOperationPreview>;
    bulkOperation(agentProfileId: string, applicationProfileId: string, request: BulkOperationRequest, config?: RequestConfig): Observable<BulkOperationResult>;
    getAgentApplicationInfoById(applicationId: string, config?: RequestConfig): Observable<AgentApplicationInfo>;
    getAgentApplicationsByAgentId(agentId: string, pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentApplicationInfo>>;
    getAgentApplicationByRelatedEntity(entityType: string, entityId: string, config?: RequestConfig): Observable<AgentApplication>;
    updateAgentApplication(application: AgentApplication, config?: RequestConfig): Observable<AgentApplication>;
    installAgentApp(request: AgentAppEventRequest, config?: RequestConfig): Observable<AgentAppInstallResponse>;
    createAgentAppEvent(applicationId: string, request: AgentAppEventRequest, config?: RequestConfig): Observable<AgentAppEvent>;
    cancelAgentAppEvent(applicationId: string, eventId: string, config?: RequestConfig): Observable<void>;
    getAgentAppEventById(eventId: string, config?: RequestConfig): Observable<AgentAppEvent>;
    getAgentAppEvents(applicationId: string, pageLink: PageLink, actionType?: string, processingStatus?: string, config?: RequestConfig): Observable<PageData<AgentAppEvent>>;
    getAgentAppEventsByAgentId(agentId: string, pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentAppEvent>>;
    getAgentAppEventInfosByAgentId(agentId: string, pageLink: PageLink, actionType?: string, processingStatus?: string, config?: RequestConfig): Observable<PageData<AgentAppEventInfo>>;
    mergeForPreview(templateVersion: string, appType: AgentApplicationType, application?: AgentApplication, composeType?: string, relatedEntityId?: EntityId, actionType?: AgentAppEventActionType, setHostValues?: boolean, config?: RequestConfig): Observable<AgentApplication>;
    assignRelatedEntity(applicationId: string, relatedEntityId: EntityId, config?: RequestConfig): Observable<AgentApplication>;
    unassignRelatedEntity(applicationId: string, config?: RequestConfig): Observable<AgentApplication>;
    detachFromProfile(applicationId: string, config?: RequestConfig): Observable<void>;
    attachToProfile(applicationId: string, profileId: string, config?: RequestConfig): Observable<void>;
    getLatestAgentAppTemplate(appType: string, configType: string, config?: RequestConfig): Observable<AgentAppTemplate>;
    getAgentAppTemplateByVersion(appType: string, configType: string, version: string, config?: RequestConfig): Observable<AgentAppTemplate>;
    getAgentAppTemplates(config?: RequestConfig): Observable<AgentAppTemplate[]>;
    getAgentAppProfilesByAppType(appType: string, config?: RequestConfig): Observable<AgentAppProfileInfo[]>;
    getAgentAppTemplatesByAppType(appType: string, configType?: string, config?: RequestConfig): Observable<AgentAppTemplate[]>;
    getAgentAppProfileById(profileId: string, config?: RequestConfig): Observable<AgentAppProfile>;
    getAgentAppProfileInfoById(profileId: string, config?: RequestConfig): Observable<AgentAppProfileInfo>;
    saveAgentAppProfile(profile: AgentAppProfile, config?: RequestConfig): Observable<AgentAppProfile>;
    deleteAgentAppProfile(profileId: string, config?: RequestConfig): Observable<void>;
    getTenantAgentAppProfiles(pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentAppProfile>>;
    getAgentAppProfilesByIds(profileIds: string[], config?: RequestConfig): Observable<AgentAppProfile[]>;
    materializeAgentAppProfile(appType: AgentApplicationType, templateVersion: string, composeType?: string, config?: RequestConfig): Observable<AgentAppProfile>;
    mergeProfileForPreview(templateVersion: string, profile?: AgentAppProfile, composeType?: string, actionType?: AgentAppEventActionType, setHostValues?: boolean, config?: RequestConfig): Observable<AgentAppProfile>;
    getAgentAppUnits(applicationId: string, pageLink: PageLink, type?: string, config?: RequestConfig): Observable<PageData<AgentAppUnit>>;
    getAgentBulkAction(bulkActionId: string, config?: RequestConfig): Observable<AgentBulkAction>;
    getAgentProfileBulkActions(agentProfileId: string, pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentBulkAction>>;
    getAgentProfileAppProfileBulkActions(agentProfileId: string, applicationProfileId: string, pageLink: PageLink, config?: RequestConfig): Observable<PageData<AgentBulkAction>>;
    getAgentBulkActionEventStats(bulkActionId: string, config?: RequestConfig): Observable<AgentBulkActionEventStats>;
    getAgentBulkActionEvents(bulkActionId: string, pageLink: PageLink, actionType?: string, processingStatus?: string, config?: RequestConfig): Observable<PageData<AgentAppEventInfo>>;
    getRelatedEntityCandidates(entityType: EntityType, pageLink: PageLink, currentEntityId?: string, config?: RequestConfig): Observable<PageData<EntityInfoData>>;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<AgentService>;
}
