import { OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { MatDialogRef } from '@angular/material/dialog';
import { DialogComponent } from '@shared/components/dialog.component';
import { TranslateService } from '@ngx-translate/core';
import { AgentService } from '@core/http/agent.service';
import { StepperOrientation } from '@angular/material/stepper';
import { BreakpointObserver } from '@angular/cdk/layout';
import { Observable } from 'rxjs';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { AgentAppProfile, AgentApplicationType, AgentAppTemplate } from '@shared/models/agent.models';
import { EdgeTemplateCompatibilityService } from '@home/pages/agent/util/edge-template-compatibility.service';
import * as i0 from "@angular/core";
export interface AgentAppProfileWizardData {
    profile?: AgentAppProfile;
    lockedAppType?: AgentApplicationType;
    presetName?: string;
}
interface TypeCard {
    type: AgentApplicationType;
    icon: string;
    labelKey: string;
    descKey: string;
}
export declare class AgentAppProfileWizardComponent extends DialogComponent<AgentAppProfileWizardComponent, AgentAppProfile> implements OnInit {
    protected store: Store<AppState>;
    protected router: Router;
    protected translate: TranslateService;
    private agentService;
    private breakpointObserver;
    private edgeTemplateCompatibility;
    private fb;
    data: AgentAppProfileWizardData;
    dialogRef: MatDialogRef<AgentAppProfileWizardComponent, AgentAppProfile>;
    proposedYaml: string;
    currentYaml: string;
    typeCards: TypeCard[];
    selectedType: AgentApplicationType | null;
    template: AgentAppTemplate | null;
    composeType: string | null;
    composeTypeKeys: string[];
    loadingTemplate: boolean;
    loadError: string;
    availableTemplates: AgentAppTemplate[];
    selectedTemplateVersion: string | null;
    loadingTemplates: boolean;
    private templatesByTypeCache;
    profileForm: UntypedFormGroup;
    composeYaml: string;
    diffSyncScroll: boolean;
    submitting: boolean;
    stepperOrientation: Observable<StepperOrientation>;
    stepperLabelPosition: Observable<'bottom' | 'end'>;
    get lockedAppType(): AgentApplicationType | null;
    get editMode(): boolean;
    get profileName(): string;
    get profileDescription(): string;
    constructor(store: Store<AppState>, router: Router, translate: TranslateService, agentService: AgentService, breakpointObserver: BreakpointObserver, edgeTemplateCompatibility: EdgeTemplateCompatibilityService, fb: UntypedFormBuilder, data: AgentAppProfileWizardData, dialogRef: MatDialogRef<AgentAppProfileWizardComponent, AgentAppProfile>);
    ngOnInit(): void;
    get titleKey(): string;
    get profileNamePlaceholder(): string;
    private initForEdit;
    selectType(type: AgentApplicationType): void;
    private loadTemplatesForType;
    private supportedTemplates;
    private selectLatestTemplate;
    onTemplateSelected(version: string): void;
    private applyTemplate;
    composeTypeLabel(composeType: string): string;
    onComposeTypeChange(composeType: string): void;
    private rebuildComposePreview;
    cancel(): void;
    canProceedFromType(): boolean;
    canSubmit(): boolean;
    isComposeYamlInvalid(): boolean;
    submit(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppProfileWizardComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppProfileWizardComponent, "tb-agent-app-profile-wizard", never, {}, {}, never, never, false, never>;
}
export {};
