import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { MatAutocomplete } from '@angular/material/autocomplete';
import { TruncatePipe } from '@shared/pipe/truncate.pipe';
import { AgentInfo } from '@shared/models/agent.models';
import { AgentService } from '@core/http/agent.service';
import { AgentCreateDialogService } from '@home/pages/agent/agent-create-dialog.service';
import * as i0 from "@angular/core";
export declare class AgentAutocompleteComponent implements ControlValueAccessor, OnInit {
    translate: TranslateService;
    truncate: TruncatePipe;
    private agentService;
    private fb;
    private agentCreateDialog;
    selectAgentFormGroup: UntypedFormGroup;
    modelValue: AgentInfo | null;
    filteredAgents: Observable<Array<AgentInfo>>;
    searchText: string;
    agentInput: ElementRef;
    agentAutocomplete: MatAutocomplete;
    private dirty;
    private propagateChange;
    constructor(translate: TranslateService, truncate: TruncatePipe, agentService: AgentService, fb: UntypedFormBuilder, agentCreateDialog: AgentCreateDialogService);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: AgentInfo | null): void;
    onFocus(): void;
    updateView(agent: AgentInfo | null): void;
    displayAgentFn(agent?: AgentInfo): string | undefined;
    fetchAgents(searchText?: string): Observable<Array<AgentInfo>>;
    clear(): void;
    textIsNotEmpty(text: string): boolean;
    createAgent($event: Event): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAutocompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAutocompleteComponent, "tb-agent-autocomplete", never, {}, {}, never, never, false, never>;
}
