import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { MatFormFieldAppearance } from '@angular/material/form-field';
import { Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { AgentService } from '@core/http/agent.service';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import { AgentAppProfile } from '@shared/models/agent.models';
import { appProfileTrackKey } from '@home/pages/agent/util/virtual-app-profiles';
import { EdgeTemplateCompatibilityService } from '@home/pages/agent/util/edge-template-compatibility.service';
import * as i0 from "@angular/core";
export declare class AgentAppProfileListComponent implements ControlValueAccessor, OnInit {
    private agentService;
    private translate;
    private userPermissionsService;
    private edgeTemplateCompatibility;
    private fb;
    private static readonly PROFILES_PAGE_SIZE;
    labelText: string;
    placeholderText: string;
    appearance: MatFormFieldAppearance;
    disabled: boolean;
    readonly canCreateAppProfile: boolean;
    listFormGroup: UntypedFormGroup;
    selected: AgentAppProfile[];
    filteredEntries: Observable<AgentAppProfile[]>;
    materializing: boolean;
    errorText: string;
    readonly trackKey: typeof appProfileTrackKey;
    profileInput: ElementRef<HTMLInputElement>;
    private modelValue;
    private realProfiles;
    private templatesByType;
    private allEntries$;
    private entriesLoaded;
    private pendingSelectionIds;
    private propagateChange;
    constructor(agentService: AgentService, translate: TranslateService, userPermissionsService: UserPermissionsService, edgeTemplateCompatibility: EdgeTemplateCompatibilityService, fb: UntypedFormBuilder);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string[] | null): void;
    private resolveSelection;
    private applySelection;
    isVirtual(profile: AgentAppProfile): boolean;
    templateLabel(profile: AgentAppProfile): string;
    displayFn(profile?: AgentAppProfile): string | undefined;
    remove(profile: AgentAppProfile): void;
    private onEntrySelected;
    private materialize;
    private addProfile;
    private filterEntries;
    private loadEntries;
    private mergeRealProfiles;
    private refreshEntries;
    private clearInput;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppProfileListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppProfileListComponent, "tb-agent-app-profile-list", never, { "labelText": { "alias": "labelText"; "required": false; }; "placeholderText": { "alias": "placeholderText"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; }, {}, never, ["[matSuffix]"], false, never>;
}
