import { ChangeDetectorRef, OnInit } from '@angular/core';
import { PlatformFeature, PlatformFeatureOfferInfo } from '@shared/models/subscription.models';
import { ActivatedRoute, Router } from '@angular/router';
import { IntegrationType } from '@shared/models/integration.models';
import { WhiteLabelingService } from '@core/http/white-labeling.service';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { NotificationService } from '@core/http/notification.service';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export declare class RequestPePackComponent implements OnInit {
    private route;
    private router;
    private store;
    private wl;
    private translate;
    private notificationService;
    private cd;
    PlatformFeature: typeof PlatformFeature;
    feature: PlatformFeature;
    offerInfo: PlatformFeatureOfferInfo;
    integrationTypes: IntegrationType[];
    pePackRequested: boolean;
    sendError: boolean;
    sendNetworkError: boolean;
    sendErrorMessage: string | null;
    get customerUser(): boolean;
    constructor(route: ActivatedRoute, router: Router, store: Store<AppState>, wl: WhiteLabelingService, translate: TranslateService, notificationService: NotificationService, cd: ChangeDetectorRef);
    ngOnInit(): void;
    integrationName(type: IntegrationType): string;
    openIntegrationGuide(type: IntegrationType): void;
    requestAccess(): void;
    gotoPage(page: string): void;
    private gotoHelpPage;
    private storePePackRequested;
    private restorePePackRequested;
    private clearSendErrors;
    private onSendError;
    static ɵfac: i0.ɵɵFactoryDeclaration<RequestPePackComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<RequestPePackComponent, "tb-request-pe-pack", never, {}, {}, never, never, false, never>;
}
