import { AfterViewInit, ElementRef, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { BreakpointObserver } from '@angular/cdk/layout';
import { PageComponent } from '@shared/components/page.component';
import { AppState } from '@core/core.state';
import { MatSidenav } from '@angular/material/sidenav';
import { AuthState } from '@core/auth/auth.models';
import { ISearchableComponent } from '@home/models/searchable-component.models';
import { ActiveComponentService } from '@core/services/active-component.service';
import { FormBuilder } from '@angular/forms';
import { WhiteLabelingService } from '@core/http/white-labeling.service';
import { TranslateService } from '@ngx-translate/core';
import { AiAssistantPanelService } from '@core/services/ai-assistant-panel.service';
import { HomeService } from '@core/services/home.service';
import * as i0 from "@angular/core";
export declare class HomeComponent extends PageComponent implements AfterViewInit, OnInit, OnDestroy {
    protected store: Store<AppState>;
    private window;
    private activeComponentService;
    private fb;
    private renderer;
    wl: WhiteLabelingService;
    translate: TranslateService;
    breakpointObserver: BreakpointObserver;
    homeService: HomeService;
    panelService: AiAssistantPanelService;
    authState: AuthState;
    forceFullscreen: boolean;
    activeComponent: any;
    searchableComponent: ISearchableComponent;
    sidenavMode: 'over' | 'push' | 'side';
    sidenavOpened: boolean;
    sidenavDesktop: import("@angular/core").WritableSignal<boolean>;
    sidenavCollapsed: import("@angular/core").WritableSignal<boolean>;
    menuCollapsed: import("@angular/core").Signal<boolean>;
    sidenav: MatSidenav;
    sidebarScroll: ElementRef<HTMLElement>;
    sideMenu: ElementRef<HTMLElement>;
    navHeader: ElementRef<HTMLElement>;
    sidebarBottom: ElementRef<HTMLElement>;
    mainContent: ElementRef<HTMLElement>;
    searchInputField: ElementRef;
    fullscreenEnabled: boolean;
    searchEnabled: boolean;
    showSearch: boolean;
    textSearch: import("@angular/forms").FormControl<string>;
    private updateScrollShadows;
    private scrollShadowWatcher$;
    private sidebarScrollUnlisten;
    private destroy$;
    constructor(store: Store<AppState>, window: Window, activeComponentService: ActiveComponentService, fb: FormBuilder, renderer: Renderer2, wl: WhiteLabelingService, translate: TranslateService, breakpointObserver: BreakpointObserver, homeService: HomeService, panelService: AiAssistantPanelService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    sidenavClicked(): void;
    toggleSidenav(): void;
    toggleFullscreen(): void;
    isFullscreen(): boolean;
    goBack(): void;
    activeComponentChanged(activeComponent: any): void;
    private _updateScrollShadows;
    private updateActiveComponent;
    displaySearchMode(): boolean;
    openSearch(): void;
    closeSearch(): void;
    platformNameAndVersion$(): Observable<string>;
    private searchTextUpdated;
    static ɵfac: i0.ɵɵFactoryDeclaration<HomeComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<HomeComponent, "tb-home", never, {}, {}, never, never, false, never>;
}
