import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { DatePipe } from '@angular/common';
import { Notification } from '@shared/models/notification.models';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import { NotificationService } from '@core/http/notification.service';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { ActivatedRouteSnapshot } from '@angular/router';
import { UtilsService } from '@core/services/utils.service';
import { DomSanitizer } from '@angular/platform-browser';
import * as i0 from "@angular/core";
export declare class InboxTableConfigResolver {
    private store;
    private notificationService;
    private translate;
    private dialog;
    private datePipe;
    private utilsService;
    private sanitizer;
    private userPermissionsService;
    private readonly config;
    constructor(store: Store<AppState>, notificationService: NotificationService, translate: TranslateService, dialog: MatDialog, datePipe: DatePipe, utilsService: UtilsService, sanitizer: DomSanitizer, userPermissionsService: UserPermissionsService);
    resolve(_route: ActivatedRouteSnapshot): EntityTableConfig<Notification>;
    private configureCellActions;
    private markAllRead;
    private markAsRead;
    private showNotification;
    static ɵfac: i0.ɵɵFactoryDeclaration<InboxTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<InboxTableConfigResolver>;
}
