import { ChangeDetectorRef, ElementRef, OnInit, Type } from '@angular/core';
import { WidgetContext } from '@home/models/widget-component.models';
import { DynamicComponentFactoryService } from '@core/services/dynamic-component-factory.service';
import { ExceptionData } from '@shared/models/error.models';
import { UtilsService } from '@core/services/utils.service';
import { ResourcesService } from '@core/services/resources.service';
import { IModulesMap } from '@modules/common/modules-map.models';
import { TbAnchorComponent } from '@shared/components/tb-anchor.component';
import * as i0 from "@angular/core";
export declare class HtmlContainerWidgetComponent implements OnInit {
    private elementRef;
    private modulesMap;
    private sharedModule;
    private widgetComponentsModule;
    private homeComponentsModule;
    private dynamicComponentFactoryService;
    private utils;
    private cdr;
    private resources;
    containerElmRef: ElementRef<HTMLElement>;
    angularContainer: TbAnchorComponent;
    ctx: WidgetContext;
    private containerInstanceComponentType;
    private settings;
    widgetErrorData: ExceptionData;
    constructor(elementRef: ElementRef<HTMLElement>, modulesMap: IModulesMap, sharedModule: Type<any>, widgetComponentsModule: Type<any>, homeComponentsModule: Type<any>, dynamicComponentFactoryService: DynamicComponentFactoryService, utils: UtilsService, cdr: ChangeDetectorRef, resources: ResourcesService);
    ngOnInit(): void;
    private initPlain;
    private compileAndExecutePlainFunction;
    private initAngular;
    private compileAngularFunction;
    private initAngularComponent;
    private destroyContainerInstanceResources;
    private handleWidgetException;
    private loadWidgetResources;
    private loadAngularModules;
    static ɵfac: i0.ɵɵFactoryDeclaration<HtmlContainerWidgetComponent, [null, { optional: true; }, null, null, null, null, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<HtmlContainerWidgetComponent, "tb-html-container-widget", never, { "ctx": { "alias": "ctx"; "required": false; }; }, {}, never, never, false, never>;
}
