import { ChangeDetectorRef, NgZone, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Location } from '@angular/common';
import { AgentService } from '@core/http/agent.service';
import { AttributeService } from '@core/http/attribute.service';
import { TelemetryWebsocketService } from '@core/ws/telemetry-websocket.service';
import { LogViewerComponent } from './log-viewer.component';
import { MetricsSnapshot } from '@home/pages/agent/util/agent-metrics';
import * as i0 from "@angular/core";
export declare class AgentAppUnitLogViewerPageComponent implements OnInit, OnDestroy {
    private route;
    private router;
    private location;
    private agentService;
    private attributeService;
    private telemetryWsService;
    private zone;
    private cdr;
    logViewer: LogViewerComponent;
    unitIdentifier: string;
    appType: string;
    image: string;
    state: string;
    agentOnline: boolean;
    metrics: MetricsSnapshot;
    private destroy$;
    private logSub;
    private activeSub;
    private unitAttrSub;
    private metricsSub;
    private lastSeenLogSeq;
    private unitId;
    private applicationId;
    private agentId;
    constructor(route: ActivatedRoute, router: Router, location: Location, agentService: AgentService, attributeService: AttributeService, telemetryWsService: TelemetryWebsocketService, zone: NgZone, cdr: ChangeDetectorRef);
    back(): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
    private subscribeToMetrics;
    private loadHeader;
    private subscribeToUnitAttributes;
    private subscribeToLogs;
    private tearDownLogs;
    private subscribeToAgentActive;
    private onAgentActiveChanged;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppUnitLogViewerPageComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppUnitLogViewerPageComponent, "tb-agent-app-unit-log-viewer-page", never, {}, {}, never, never, false, never>;
}
