import { ChangeDetectorRef, DestroyRef, OnDestroy, Renderer2, ViewContainerRef } from '@angular/core';
import { EntityService } from '@core/http/entity.service';
import { EntityType } from '@shared/models/entity-type.models';
import { ControlValueAccessor } from '@angular/forms';
import { MatButton, MatIconButton } from '@angular/material/button';
import { TbPopoverService } from '@shared/components/popover.service';
import { AgentAppArgument, AgentAppArgumentSource } from '@shared/models/agent.models';
import * as i0 from "@angular/core";
export declare class AgentAppArgumentsComponent implements ControlValueAccessor, OnDestroy {
    private popoverService;
    private viewContainerRef;
    private renderer;
    private entityService;
    private destroyRef;
    private cd;
    set disabled(value: boolean);
    get disabled(): boolean;
    private inputDisabled;
    private cvaDisabled;
    arguments: AgentAppArgument[];
    expanded: boolean;
    displayColumns: string[];
    readonly argumentSourceTranslationMap: Map<AgentAppArgumentSource, string>;
    readonly tokenExample = "${tb.<name>}";
    entityNameMap: Map<string, string>;
    private popoverComponent;
    private propagateChange;
    constructor(popoverService: TbPopoverService, viewContainerRef: ViewContainerRef, renderer: Renderer2, entityService: EntityService, destroyRef: DestroyRef, cd: ChangeDetectorRef);
    ngOnDestroy(): void;
    getEntityDetailsPageURL(id: string, entityType: EntityType): string;
    registerOnChange(fn: (value: AgentAppArgument[]) => void): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: AgentAppArgument[]): void;
    private updateEntityNameMap;
    formatLabel(argument: AgentAppArgument): string;
    typeLabel(argument: AgentAppArgument): string;
    onDelete($event: Event, index: number): void;
    manageArgument($event: Event, matButton: MatButton | MatIconButton, index?: number): void;
    private updateModel;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppArgumentsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppArgumentsComponent, "tb-agent-app-arguments", never, { "disabled": { "alias": "disabled"; "required": false; }; }, {}, never, never, false, never>;
}
