import { DestroyRef, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityType } from '@shared/models/entity-type.models';
import { EntityFilter } from '@shared/models/query/query.models';
import { TranslateService } from '@ngx-translate/core';
import { TbPopoverComponent } from '@shared/components/popover.component';
import { AgentAppArgument, AgentAppArgumentFormat, AgentAppArgumentSource, AgentAppArgumentValueType } from '@shared/models/agent.models';
import { AttributeScope, DataKeyType } from '@shared/models/telemetry/telemetry.models';
import * as i0 from "@angular/core";
export declare class AgentAppArgumentPanelComponent implements OnInit {
    private fb;
    private translate;
    private store;
    private destroyRef;
    private popover;
    argument: AgentAppArgument;
    buttonTitle: string;
    usedNames: string[];
    readonly: boolean;
    argumentApplied: import("@angular/core").OutputEmitterRef<AgentAppArgument>;
    argumentSources: AgentAppArgumentSource[];
    argumentSourceTranslationMap: Map<AgentAppArgumentSource, string>;
    argumentSourceEntityTypeMap: Map<AgentAppArgumentSource, import("@shared/models/agent.models").AgentAppArgumentSourceEntityParams>;
    argumentValueTypes: AgentAppArgumentValueType[];
    argumentValueTypeTranslationMap: Map<AgentAppArgumentValueType, string>;
    attributeScopes: AttributeScope[];
    attributeScopeTranslationMap: Map<import("@shared/models/telemetry/telemetry.models").TelemetryType, string>;
    argumentFormats: AgentAppArgumentFormat[];
    argumentFormatTranslationMap: Map<AgentAppArgumentFormat, string>;
    readonly AgentAppArgumentValueType: typeof AgentAppArgumentValueType;
    readonly DataKeyType: typeof DataKeyType;
    argumentFormGroup: FormGroup;
    keyEntityFilter: EntityFilter;
    private readonly tenantId;
    constructor(fb: FormBuilder, translate: TranslateService, store: Store<AppState>, destroyRef: DestroyRef, popover: TbPopoverComponent<AgentAppArgumentPanelComponent>);
    get isAttribute(): boolean;
    get sourceType(): AgentAppArgumentSource;
    get isEntitySource(): boolean;
    get sourceEntityType(): EntityType;
    get keyDataType(): DataKeyType;
    get keyAutocompleteEnabled(): boolean;
    private updateKeyEntityFilter;
    get formatHint(): string;
    ngOnInit(): void;
    private updateSourceEntityValidators;
    get nameReference(): string;
    apply(): void;
    cancel(): void;
    private uniqueNameValidator;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppArgumentPanelComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppArgumentPanelComponent, "tb-agent-app-argument-panel", never, { "argument": { "alias": "argument"; "required": false; }; "buttonTitle": { "alias": "buttonTitle"; "required": false; }; "usedNames": { "alias": "usedNames"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; }, { "argumentApplied": "argumentApplied"; }, never, never, false, never>;
}
