import { DestroyRef } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { Router } from '@angular/router';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { DialogComponent } from '@shared/components/dialog.component';
import { TranslateService } from '@ngx-translate/core';
import { MatStepper } from '@angular/material/stepper';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { BreakpointObserver } from '@angular/cdk/layout';
import { Observable } from 'rxjs';
import { AgentApplicationType, AgentProfile, AgentProfileInfo } from '@shared/models/agent.models';
import { AgentService } from '@core/http/agent.service';
import { AgentProfileCreateDialogService } from '@home/pages/agent/agent-profile-create-dialog.service';
import * as i0 from "@angular/core";
type ValidationState = 'idle' | 'validating' | 'valid' | 'invalid-strategy' | 'invalid-no-edge-app';
export interface AgentAutoProvisionDialogData {
    appType?: AgentApplicationType;
}
export declare class AgentAutoProvisionDialogComponent extends DialogComponent<AgentAutoProvisionDialogComponent, boolean> {
    protected store: Store<AppState>;
    protected router: Router;
    protected translate: TranslateService;
    private agentService;
    private fb;
    private dialog;
    private agentProfileCreateDialogService;
    private breakpointObserver;
    private destroyRef;
    data: AgentAutoProvisionDialogData;
    dialogRef: MatDialogRef<AgentAutoProvisionDialogComponent, boolean>;
    selectForm: UntypedFormGroup;
    filteredProfiles$: Observable<AgentProfileInfo[]>;
    selectedProfile: AgentProfile | null;
    validation: ValidationState;
    searchText: string;
    loading: boolean;
    stepper: MatStepper;
    private autocompleteTrigger;
    stepperLabelPosition: Observable<'bottom' | 'end'>;
    get appType(): AgentApplicationType | null;
    private get i18nPrefix();
    get titleKey(): string;
    get infoTitleKey(): string;
    get infoBodyKey(): string;
    get stepSelectKey(): string;
    get stepScriptKey(): string;
    get validKey(): string;
    get invalidNoAppKey(): string;
    get successMessageKey(): string;
    get scriptHintKey(): string;
    constructor(store: Store<AppState>, router: Router, translate: TranslateService, agentService: AgentService, fb: UntypedFormBuilder, dialog: MatDialog, agentProfileCreateDialogService: AgentProfileCreateDialogService, breakpointObserver: BreakpointObserver, destroyRef: DestroyRef, data: AgentAutoProvisionDialogData, dialogRef: MatDialogRef<AgentAutoProvisionDialogComponent, boolean>);
    onProfileFocus(): void;
    fetchEligibleProfiles(searchText?: string): Observable<AgentProfileInfo[]>;
    displayProfile(profile?: AgentProfileInfo): string;
    onProfileSelected(profile: AgentProfileInfo): void;
    private validateProfile;
    canProceed(): boolean;
    createNewProfile($event: Event): void;
    openSelectedProfile(): void;
    assignProfileToSelected($event: Event): void;
    dockerCommand: string;
    proceedToScript(): void;
    hasCredentials(): boolean;
    onCopied(): void;
    cancel(): void;
    goToProfile(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAutoProvisionDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAutoProvisionDialogComponent, "tb-agent-auto-provision-dialog", never, {}, {}, never, never, false, never>;
}
export {};
