import { DestroyRef, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { AiChatMessagesComponent } from '@home/components/ai/ai-chat-messages.component';
import { PageComponent } from '@shared/components/page.component';
import { DomSanitizer } from '@angular/platform-browser';
import { ActivatedRoute, Router } from '@angular/router';
import { ChatMessage, DashboardsOverview, SolutionCreatorInfo, SolutionDescriptor, SolutionMetadata, SolutionStep } from '@shared/models/solution-creator.models';
import { AiPromptInputComponent } from '@home/components/ai/ai-prompt-input.component';
import { SolutionsCreatorService } from '@core/http/solutions-creator.service';
import { DialogService } from '@core/services/dialog.service';
import { TranslateService } from '@ngx-translate/core';
import { SolutionSideBarComponent } from '@home/pages/ai-solution-creator/side-bar/solution-side-bar.component';
import { DynamicMatDialog } from '@shared/components/dialog/dynamic/dynamic-dialog';
import * as i0 from "@angular/core";
export declare class SolutionCreatorComponent extends PageComponent implements OnInit, OnDestroy {
    private route;
    private solutionCreator;
    private router;
    private destroyRef;
    private elementRef;
    private dialogService;
    private translate;
    private sanitizer;
    private dynamicMatDialog;
    promptInput: AiPromptInputComponent;
    chatMessages: AiChatMessagesComponent;
    solutionSideBar: SolutionSideBarComponent;
    isReadyStep: import("@angular/core").WritableSignal<boolean>;
    skipInterviewAllowed: import("@angular/core").WritableSignal<boolean>;
    solutionStep: import("@angular/core").WritableSignal<SolutionStep>;
    creatorStep: import("@angular/core").WritableSignal<"result" | "chat">;
    messages: import("@angular/core").WritableSignal<ChatMessage[]>;
    loading: import("@angular/core").WritableSignal<boolean>;
    loadingLongTime: import("@angular/core").WritableSignal<boolean>;
    isGenerating: import("@angular/core").WritableSignal<boolean>;
    showMoreExamples: import("@angular/core").WritableSignal<boolean>;
    isInitialEmpty: import("@angular/core").Signal<boolean>;
    activePlaceholder: import("@angular/core").Signal<"solution-creator.describe-solution-you-want" | "solution-creator.enter-your-prompt">;
    activeStepIndex: import("@angular/core").Signal<0 | 1 | 2 | -1>;
    stepperLabels: string[];
    stepStatuses: import("@angular/core").WritableSignal<("active" | "pending" | "ready")[]>;
    goToStep(index: number): void;
    private updateStepStatuses;
    solutionExamples: Array<{
        key: string;
        labelKey: string;
        icon: string;
        message: string;
    }>;
    SolutionStep: typeof SolutionStep;
    solutionDescriptor: SolutionDescriptor;
    dashboardsOverview: DashboardsOverview[];
    solutionName: string;
    loadingImage: string;
    private solutionId;
    private _solutionInfo;
    private get solutionInfo();
    private set solutionInfo(value);
    private messages$;
    private forceScroll;
    private cancelPending$;
    private loadingTimer;
    constructor(route: ActivatedRoute, solutionCreator: SolutionsCreatorService, router: Router, destroyRef: DestroyRef, elementRef: ElementRef, dialogService: DialogService, translate: TranslateService, sanitizer: DomSanitizer, dynamicMatDialog: DynamicMatDialog);
    ngOnInit(): void;
    ngOnDestroy(): void;
    nextStep(): void;
    installSolution(): void;
    uninstallSolution(): void;
    startOver(): void;
    back(): void;
    updatedSolutionDescriptor(descriptor: SolutionDescriptor): void;
    updatedDashboardOverview(dashboards: DashboardsOverview[]): void;
    get solutionMetadata(): Partial<SolutionMetadata>;
    get nextButtonLabel(): string;
    updatedSolution($event: SolutionCreatorInfo): void;
    onInstalledChanged($event: {
        solutionId: string;
        installed: boolean;
    }): void;
    startCreateSolution(key: string): void;
    gotoMainDashboard(openInfoDialog?: boolean): void;
    openInfo(): void;
    private sendMessage;
    private sendDashboardConfigurationMsg;
    private updatedCurrentMsg;
    private showErrorMessage;
    private resetSolution;
    private initPredefinedSolution;
    private initGenerateState;
    toggleMoreExamples(): void;
    skipInterview(): void;
    sendMsgFromUser(msg: string): void;
    private initLoadingState;
    private stopLoadingState;
    static ɵfac: i0.ɵɵFactoryDeclaration<SolutionCreatorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SolutionCreatorComponent, "tb-solution-creator", never, {}, {}, never, never, false, never>;
}
