import { AbstractControl, ControlValueAccessor, UntypedFormArray, UntypedFormBuilder, UntypedFormGroup, ValidationErrors, Validator } from '@angular/forms';
import { ThemePalette } from '@angular/material/core';
import { Instance, ResourceSettingTelemetry } from './lwm2m-profile-config.models';
import { TranslateService } from '@ngx-translate/core';
import { GtSmBreakpointAwareDirective } from '@shared/components/gt-sm-breakpoint-aware.directive';
import * as i0 from "@angular/core";
export declare class Lwm2mObserveAttrTelemetryInstancesComponent extends GtSmBreakpointAwareDirective implements ControlValueAccessor, Validator {
    private fb;
    translate: TranslateService;
    readonly resourceToggles: {
        type: ResourceSettingTelemetry;
        color: ThemePalette;
        labelKey: string;
    }[];
    instancesFormGroup: UntypedFormGroup;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    disabled: boolean;
    private propagateChange;
    constructor(fb: UntypedFormBuilder, translate: TranslateService);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: Instance[]): void;
    validate(control: AbstractControl): ValidationErrors | null;
    get instancesFormArray(): UntypedFormArray;
    private updateInstances;
    private createInstanceFormGroup;
    private updateModel;
    changeInstanceResourcesCheckBox: (value: boolean, instance: AbstractControl, type: ResourceSettingTelemetry) => void;
    private updateValidators;
    getIndeterminate: (instance: AbstractControl, type: ResourceSettingTelemetry) => boolean;
    getChecked: (instance: AbstractControl, type: ResourceSettingTelemetry) => boolean;
    disableObserve(instance: AbstractControl): boolean;
    isToggleDisabled(instance: AbstractControl, type: ResourceSettingTelemetry): boolean;
    get isExpend(): boolean;
    getNameInstance(instance: Instance): string;
    disableObserveInstance: (instance: AbstractControl) => boolean;
    observeInstance: (instance: AbstractControl) => boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<Lwm2mObserveAttrTelemetryInstancesComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<Lwm2mObserveAttrTelemetryInstancesComponent, "tb-profile-lwm2m-observe-attr-telemetry-instances", never, { "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; }, {}, never, never, false, never>;
}
