import { ChangeDetectorRef, EventEmitter, TemplateRef } from '@angular/core';
import { WidgetsBundle } from '@shared/models/widgets-bundle.model';
import { IAliasController } from '@core/api/widget-api.models';
import { WidgetService } from '@core/http/widget.service';
import { DeprecatedFilter, WidgetInfo, widgetType, WidgetTypeInfo } from '@shared/models/widget.models';
import { Direction } from '@shared/models/page/sort-order';
import { GridEntitiesFetchFunction, ScrollGridColumns } from '@shared/components/grid/scroll-grid-datasource';
import { ItemSizeStrategy } from '@shared/components/grid/scroll-grid.component';
import { TranslateService } from '@ngx-translate/core';
import { MpItemVersionView } from '@shared/models/iot-hub/iot-hub-version.models';
import { FilterParamInfo, WidgetCategory } from '@shared/models/iot-hub/iot-hub-item.models';
import { IotHubApiService } from '@core/http/iot-hub-api.service';
import { IotHubActionsService } from '@home/components/iot-hub/iot-hub-actions.service';
import { IotHubFilterGroup } from '@home/components/iot-hub/iot-hub-utils';
import { IotHubBuiltInService } from '@home/components/iot-hub/iot-hub-built-in.service';
import { Operation, Resource } from '@shared/models/security.models';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { WhiteLabelingService } from '@core/http/white-labeling.service';
import * as i0 from "@angular/core";
type selectWidgetMode = 'installed' | 'iotHub';
type installedSubMode = 'default' | 'allWidgets';
type iotHubSubMode = 'default' | 'allWidgets' | 'installed' | 'category';
interface WidgetSelectSortOption {
    value: string;
    label: string;
    direction: Direction;
}
interface WidgetsFilter {
    search: string;
    filter: widgetType[];
    deprecatedFilter: DeprecatedFilter;
}
interface BundleWidgetsFilter extends WidgetsFilter {
    widgetsBundleId: string;
}
export declare class DashboardWidgetSelectComponent {
    private widgetsService;
    private iotHubApiService;
    private iotHubActions;
    private iotHubBuiltInService;
    private translate;
    private store;
    private cd;
    wl: WhiteLabelingService;
    private searchSubject;
    private search$;
    private filterWidgetTypes$;
    private deprecatedFilter$;
    private selectWidgetMode$;
    private installedSubMode$;
    private iotHubSubMode$;
    private widgetsBundle$;
    resource: typeof Resource;
    operation: typeof Operation;
    widgetTypes: Set<widgetType>;
    hasDeprecated: boolean;
    iotHubSelectedCategory: string;
    includeDeprecated: boolean;
    searchFocused: boolean;
    iotHubSortOptions: WidgetSelectSortOption[];
    iotHubSelectedSortIndex: number;
    aliasController: IAliasController;
    scadaFirst: boolean;
    set search(search: string);
    get search(): string;
    set filterWidgetTypes(widgetTypes: Array<widgetType>);
    get filterWidgetTypes(): Array<widgetType>;
    set selectWidgetMode(mode: selectWidgetMode);
    get selectWidgetMode(): selectWidgetMode;
    set installedSubMode(sub: installedSubMode);
    get installedSubMode(): installedSubMode;
    set iotHubSubMode(sub: iotHubSubMode);
    get iotHubSubMode(): iotHubSubMode;
    set deprecatedFilter(filter: DeprecatedFilter);
    get deprecatedFilter(): DeprecatedFilter;
    set widgetsBundle(widgetBundle: WidgetsBundle);
    get widgetsBundle(): WidgetsBundle;
    iotHubFilterPanel: TemplateRef<void>;
    widgetSelected: EventEmitter<WidgetInfo>;
    closeClick: EventEmitter<void>;
    importClick: EventEmitter<Event>;
    columns: ScrollGridColumns;
    gridWidgetsItemSizeStrategy: ItemSizeStrategy;
    widgetBundlesFetchFunction: GridEntitiesFetchFunction<WidgetsBundle, string>;
    installedDefaultFetchFunction: GridEntitiesFetchFunction<any, string>;
    allWidgetsFetchFunction: GridEntitiesFetchFunction<WidgetTypeInfo, WidgetsFilter>;
    widgetsFetchFunction: GridEntitiesFetchFunction<WidgetTypeInfo, BundleWidgetsFilter>;
    iotHubWidgetsFetchFunction: GridEntitiesFetchFunction<MpItemVersionView, string>;
    iotHubInstalledWidgetsFetchFunction: GridEntitiesFetchFunction<MpItemVersionView, string>;
    iotHubDefaultFetchFunction: GridEntitiesFetchFunction<any, string>;
    readonly LOGICAL_ALL_WIDGETS = "__logical_all_widgets__";
    readonly LOGICAL_INSTALLED_FROM_IOT_HUB = "__logical_installed_from_iot_hub__";
    widgetsBundleFilter: string;
    allWidgetsFilter: WidgetsFilter;
    widgetsFilter: BundleWidgetsFilter;
    iotHubWidgetsFilter: string;
    iotHubInstalledWidgetsFilter: string;
    widgetCategoriesFilter: string;
    private installedWidgets;
    private installedWidgetVersions;
    iotHubAppliedWidgetTypes: Set<string>;
    iotHubAppliedCategories: Set<string>;
    iotHubAppliedUseCases: Set<string>;
    iotHubWidgetTypeOptions: FilterParamInfo[];
    iotHubCategoryOptions: FilterParamInfo[];
    iotHubUseCaseOptions: FilterParamInfo[];
    iotHubFilterCount: number;
    iotHubFilterSearch: Record<string, string>;
    iotHubFilterItemsHovered: boolean;
    isTenantAdmin: boolean;
    constructor(widgetsService: WidgetService, iotHubApiService: IotHubApiService, iotHubActions: IotHubActionsService, iotHubBuiltInService: IotHubBuiltInService, translate: TranslateService, store: Store<AppState>, cd: ChangeDetectorRef, wl: WhiteLabelingService);
    private prependLogicalCards;
    private resetSubModes;
    private updateWidgetTypesForCurrentState;
    onWidgetClicked(widget: WidgetTypeInfo): void;
    isSystem(item: WidgetsBundle): boolean;
    selectBundle($event: Event, bundle: WidgetsBundle): void;
    onAllWidgetsCardClicked($event: Event): void;
    onInstalledFromIotHubCardClicked($event: Event): void;
    onCategoryCardClicked($event: Event, category: WidgetCategory): void;
    getCategoryImageUrl(category: WidgetCategory): string | null;
    onIotHubWidgetClicked($event: Event, item: MpItemVersionView): void;
    isIotHubWidgetInstalled(item: MpItemVersionView): boolean;
    isIotHubWidgetBuiltIn(item: MpItemVersionView): boolean;
    getIotHubItemImage(item: MpItemVersionView): string | null;
    getIotHubWidgetTypeLabel(key: string): string;
    getFilteredIotHubItems(items: FilterParamInfo[], searchKey: string): FilterParamInfo[];
    getGroupedIotHubFilterItems(items: FilterParamInfo[], searchKey: string): IotHubFilterGroup[];
    toggleIotHubWidgetType(key: string): void;
    toggleIotHubCategory(key: string): void;
    toggleIotHubUseCase(key: string): void;
    clearIotHubFilters(): void;
    private onIotHubFiltersChanged;
    onIotHubSortChange(index: number): void;
    get totalFilterCount(): number;
    hasActiveFilters(): boolean;
    clearAllFilters(): void;
    hasActiveSearchOrFilters(): boolean;
    clearSearchAndFilters(): void;
    navigateToIotHubAllWidgets(): void;
    get hideCategoriesFilterSection(): boolean;
    onIncludeDeprecatedChange(value: boolean): void;
    isFilterVisible(): boolean;
    showTopLevelWidgetModeToggle(): boolean;
    showBackButton(): boolean;
    getHeaderTitle(): string;
    getSearchPlaceholder(): string;
    onBackClick(): void;
    onClose(): void;
    clearSearch($event: Event): void;
    onImport($event: Event): void;
    get widgetTypesList(): widgetType[];
    getWidgetTypeLabel(type: widgetType): string;
    isWidgetTypeChecked(type: widgetType): boolean;
    toggleWidgetTypeFilter(type: widgetType): void;
    private reloadIotHubWidgets;
    private selectBuiltInWidget;
    private installAndAddWidget;
    private loadIotHubFilterInfo;
    private loadWidgetCategories;
    private loadInstalledWidgets;
    private fetchInstalledWidgetVersions;
    private filterAndPaginateInstalledVersions;
    private sortInstalledVersions;
    private toWidgetInfo;
    static ɵfac: i0.ɵɵFactoryDeclaration<DashboardWidgetSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DashboardWidgetSelectComponent, "tb-dashboard-widget-select", never, { "aliasController": { "alias": "aliasController"; "required": false; }; "scadaFirst": { "alias": "scadaFirst"; "required": false; }; "search": { "alias": "search"; "required": false; }; "selectWidgetMode": { "alias": "selectWidgetMode"; "required": false; }; "deprecatedFilter": { "alias": "deprecatedFilter"; "required": false; }; }, { "widgetSelected": "widgetSelected"; "closeClick": "closeClick"; "importClick": "importClick"; }, never, never, false, never>;
}
export {};
