import { OnInit, OnDestroy, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import { Direction } from '@shared/models/page/sort-order';
import { MpItemVersionView } from '@shared/models/iot-hub/iot-hub-version.models';
import { ItemType } from '@shared/models/iot-hub/iot-hub-item.models';
import { IotHubInstalledItem } from '@shared/models/iot-hub/iot-hub-installed-item.models';
import { IotHubApiService } from '@core/http/iot-hub-api.service';
import { IotHubActionsService } from './iot-hub-actions.service';
import * as i0 from "@angular/core";
interface SearchResultGroup {
    type: ItemType;
    items: MpItemVersionView[];
}
interface SortOption {
    value: string;
    label: string;
    direction: Direction;
}
export declare class TbIotHubSearchComponent implements OnInit, OnDestroy {
    private router;
    private translate;
    private iotHubApiService;
    private iotHubActions;
    readonly ItemType: typeof ItemType;
    searchText: string;
    creatorId: string;
    showCreator: boolean;
    searchTextChange: EventEmitter<string>;
    get searchPlaceholderKey(): string;
    resultGroups: SearchResultGroup[];
    totalElements: number;
    isLoading: boolean;
    hasError: boolean;
    private retryTimer;
    pageSize: number;
    pageIndex: number;
    pageSizeOptions: number[];
    sortOptions: SortOption[];
    selectedSortIndex: number;
    installedWidgets: IotHubInstalledItem[];
    installedSolutionTemplates: IotHubInstalledItem[];
    installedDeviceCounts: Record<string, number>;
    installedCalcFieldCounts: Record<string, number>;
    installedAlarmRuleCounts: Record<string, number>;
    installedRuleChainCounts: Record<string, number>;
    private searchSubject;
    private searchSubscription;
    constructor(router: Router, translate: TranslateService, iotHubApiService: IotHubApiService, iotHubActions: IotHubActionsService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    onSearchInput(): void;
    clearSearch(): void;
    onSearchEnter(): void;
    onSortChange(index: number): void;
    get totalPages(): number;
    getPageNumbers(): number[];
    goToPage(page: number): void;
    onPageSizeChange(size: number): void;
    isCompactType(type: ItemType): boolean;
    getTypeLabel(type: ItemType): string;
    getTypeRoute(type: ItemType): string;
    navigateToType(type: ItemType): void;
    getInstalledItem(item: MpItemVersionView): IotHubInstalledItem | undefined;
    getInstalledItemsCount(item: MpItemVersionView): number;
    openItemDetail(item: MpItemVersionView): void;
    installItem(item: MpItemVersionView): void;
    updateItem(item: MpItemVersionView): void;
    deleteInstalledItem(item: MpItemVersionView): void;
    navigateToCreator(creatorId: string): void;
    retryLoadResults(): void;
    private loadResults;
    private fetchResults;
    private applyResults;
    private groupResults;
    private loadInstalledItems;
    private reloadInstalledItems;
    static ɵfac: i0.ɵɵFactoryDeclaration<TbIotHubSearchComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TbIotHubSearchComponent, "tb-iot-hub-search", never, { "searchText": { "alias": "searchText"; "required": false; }; "creatorId": { "alias": "creatorId"; "required": false; }; "showCreator": { "alias": "showCreator"; "required": false; }; }, { "searchTextChange": "searchTextChange"; }, never, ["*"], false, never>;
}
export {};
