import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, NgZone, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { IotHubApiService } from '@core/http/iot-hub-api.service';
import { TranslateService } from '@ngx-translate/core';
import { IotHubInstalledItem, ItemPublishedVersionInfo } from '@shared/models/iot-hub/iot-hub-installed-item.models';
import { MpItemVersionView } from '@shared/models/iot-hub/iot-hub-version.models';
import { IotHubActionsService } from '@home/components/iot-hub/iot-hub-actions.service';
import * as i0 from "@angular/core";
export declare class TbIotHubInstalledItemsTableComponent implements OnInit, OnChanges, AfterViewInit, OnDestroy {
    private iotHubApiService;
    private translate;
    private router;
    private iotHubActions;
    private elementRef;
    private zone;
    private cd;
    textSearch: string;
    typeFilters: string[];
    itemVersion: MpItemVersionView;
    clearFilters: EventEmitter<void>;
    hasActiveFilters(): boolean;
    get withVersionClass(): boolean;
    displayedColumns: string[];
    dataSource: IotHubInstalledItem[];
    totalElements: number;
    pageSize: number;
    pageIndex: number;
    hidePageSize: boolean;
    isLoading: boolean;
    publishedVersionMap: Map<string, ItemPublishedVersionInfo>;
    updatesChecked: boolean;
    isCheckingUpdates: boolean;
    private widgetResize$;
    sort: MatSort;
    paginator: MatPaginator;
    constructor(iotHubApiService: IotHubApiService, translate: TranslateService, router: Router, iotHubActions: IotHubActionsService, elementRef: ElementRef, zone: NgZone, cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onPageChange(event: any): void;
    getItemTypeIcon(itemType: string): string;
    deleteItem(item: IotHubInstalledItem): void;
    getItemTypeLabel(itemType: string): string;
    getItemTypeChipClass(itemType: string): string;
    viewItemDetails(item: IotHubInstalledItem): void;
    private openDeviceReviewDialog;
    openEntity(item: IotHubInstalledItem): void;
    checkForUpdates(): void;
    viewUpdateDetails(publishedInfo: ItemPublishedVersionInfo, installedItem: IotHubInstalledItem): void;
    updateItem(item: IotHubInstalledItem, publishedInfo: ItemPublishedVersionInfo): void;
    getPublishedVersionInfo(item: IotHubInstalledItem): ItemPublishedVersionInfo | undefined;
    private loadData;
    static ɵfac: i0.ɵɵFactoryDeclaration<TbIotHubInstalledItemsTableComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TbIotHubInstalledItemsTableComponent, "tb-iot-hub-installed-items-table", never, { "textSearch": { "alias": "textSearch"; "required": false; }; "typeFilters": { "alias": "typeFilters"; "required": false; }; "itemVersion": { "alias": "itemVersion"; "required": false; }; }, { "clearFilters": "clearFilters"; }, never, never, false, never>;
}
