import { EventEmitter } from '@angular/core';
import { MpItemVersionView } from '@shared/models/iot-hub/iot-hub-version.models';
import { IotHubInstalledItem } from '@shared/models/iot-hub/iot-hub-installed-item.models';
import { TranslateService } from '@ngx-translate/core';
import { IotHubApiService } from '@core/http/iot-hub-api.service';
import * as i0 from "@angular/core";
export declare class TbIotHubItemCardComponent {
    private translate;
    private iotHubApiService;
    item: MpItemVersionView;
    installedItem: IotHubInstalledItem;
    installedItemsCount: number;
    showCreator: boolean;
    showTypeChip: boolean;
    showSubtype: boolean;
    mode: 'default' | 'add';
    cardClick: EventEmitter<MpItemVersionView>;
    creatorClick: EventEmitter<string>;
    installClick: EventEmitter<MpItemVersionView>;
    updateClick: EventEmitter<MpItemVersionView>;
    deleteClick: EventEmitter<MpItemVersionView>;
    addClick: EventEmitter<MpItemVersionView>;
    guideClick: EventEmitter<MpItemVersionView>;
    constructor(translate: TranslateService, iotHubApiService: IotHubApiService);
    get showInstallCount(): boolean;
    get actionLabel(): string;
    isCompactLayout(): boolean;
    getPreviewUrl(): string | null;
    getPlaceholderIcon(): string;
    getSubtypeLabel(): string;
    isInstalled(): boolean;
    isSameVersion(): boolean;
    onCardClick(): void;
    onInstallClick(event: MouseEvent): void;
    onAddClick(event: MouseEvent): void;
    onUpdateClick(event: MouseEvent): void;
    onDeleteClick(event: MouseEvent): void;
    hasInstallGuide(): boolean;
    onGuideClick(event: MouseEvent): void;
    onCreatorClick(event: Event): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<TbIotHubItemCardComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TbIotHubItemCardComponent, "tb-iot-hub-item-card", never, { "item": { "alias": "item"; "required": false; }; "installedItem": { "alias": "installedItem"; "required": false; }; "installedItemsCount": { "alias": "installedItemsCount"; "required": false; }; "showCreator": { "alias": "showCreator"; "required": false; }; "showTypeChip": { "alias": "showTypeChip"; "required": false; }; "showSubtype": { "alias": "showSubtype"; "required": false; }; "mode": { "alias": "mode"; "required": false; }; }, { "cardClick": "cardClick"; "creatorClick": "creatorClick"; "installClick": "installClick"; "updateClick": "updateClick"; "deleteClick": "deleteClick"; "addClick": "addClick"; "guideClick": "guideClick"; }, never, never, false, never>;
}
