import { ElementRef, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { PageComponent } from '@shared/components/page.component';
import { TrendzService } from '@core/http/trendz.service';
import { TrendzStatus, TrendzSynchronizationStatus } from '@shared/models/trendz-analytics.models';
import { ActivatedRoute } from '@angular/router';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { DynamicMatDialog } from '@shared/components/dialog/dynamic/dynamic-dialog';
import { TranslateService } from '@ngx-translate/core';
import { AdminService } from '@core/http/admin.service';
import { DialogService } from '@core/services/dialog.service';
import * as i0 from "@angular/core";
export declare class TrendzSettingsComponent extends PageComponent implements OnInit {
    protected store: Store<AppState>;
    private fb;
    private trendzService;
    private route;
    private dialogService;
    private translate;
    private adminService;
    private dialog;
    private elementRef;
    trendzSettingsForm: FormGroup;
    trendzSyncInfo: TrendzStatus;
    TrendzSynchronizationStatus: typeof TrendzSynchronizationStatus;
    TrendzSynchronizationResultTypeTranslationMap: Map<import("@shared/models/trendz-analytics.models").TrendzSynchronizationResultType, string>;
    authState: import("../../../../core/public-api").AuthState;
    trendzEnabled: boolean;
    private subscriptionInfo;
    constructor(store: Store<AppState>, fb: FormBuilder, trendzService: TrendzService, route: ActivatedRoute, dialogService: DialogService, translate: TranslateService, adminService: AdminService, dialog: DynamicMatDialog, elementRef: ElementRef);
    ngOnInit(): void;
    save(): void;
    retryDiscovery(): void;
    private saveAndSync;
    private updateTrendzStatus;
    retryHealthcheck(): void;
    private initTrendzSettings;
    private addTrendzLicense;
    static ɵfac: i0.ɵɵFactoryDeclaration<TrendzSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TrendzSettingsComponent, "tb-trendz-settings", never, {}, {}, never, never, false, never>;
}
