import { DestroyRef, OnInit } from '@angular/core';
import { AbstractControl, ControlValueAccessor, FormArray, FormBuilder, FormGroup, ValidationErrors, Validator } from '@angular/forms';
import { LocationKey, LocationKeyMapping, LocationKeyValueType } from '@shared/models/location.models';
import * as i0 from "@angular/core";
export declare class LocationKeysTableComponent implements ControlValueAccessor, OnInit, Validator {
    private fb;
    private destroyRef;
    disabled: boolean;
    panelTitle: string;
    availableKeys: LocationKey[];
    locationKeyTranslations: Map<LocationKey, string>;
    locationKeyDefaultNames: Map<LocationKey, string>;
    valueTypes: LocationKeyValueType[];
    valueTypeTranslations: Map<LocationKeyValueType, string>;
    keysFormGroup: FormGroup;
    private propagateChange;
    private changeRegistered;
    private normalizationPending;
    constructor(fb: FormBuilder, destroyRef: DestroyRef);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: LocationKeyMapping[] | undefined): void;
    validate(): ValidationErrors | null;
    keysFormArray(): FormArray;
    isMandatory(keyControl: AbstractControl): boolean;
    keyOptions(keyControl: AbstractControl): LocationKey[];
    get addKeyDisabled(): boolean;
    addKey(): void;
    removeKey(index: number): void;
    keyChanged(keyControl: AbstractControl): void;
    private prepareKeysFormArray;
    private keyControl;
    private disableMandatoryKeyControls;
    private uniqueKeyNamesValidator;
    private flushNormalization;
    private updateModel;
    static ɵfac: i0.ɵɵFactoryDeclaration<LocationKeysTableComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<LocationKeysTableComponent, "tb-location-keys-table", never, { "disabled": { "alias": "disabled"; "required": false; }; "panelTitle": { "alias": "panelTitle"; "required": false; }; "availableKeys": { "alias": "availableKeys"; "required": false; }; }, {}, never, never, false, never>;
}
