import { DestroyRef, ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder, FormGroup, ValidationErrors, Validator } from '@angular/forms';
import { LocationTargetEntityConfig, LocationTargetEntityMode, LocationTargetSource } from '@shared/models/location.models';
import { WidgetActionCallbacks } from '@home/components/widget/action/manage-widget-actions.component.models';
import { Observable } from 'rxjs';
import { AttributeScope, DataKeyType } from '@shared/models/telemetry/telemetry.models';
import { EntityFilter } from '@shared/models/query/query.models';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityService } from '@core/http/entity.service';
import * as i0 from "@angular/core";
export declare class LocationTargetEntityComponent implements ControlValueAccessor, OnInit, Validator {
    private fb;
    private store;
    private entityService;
    private destroyRef;
    aliasNameInput: ElementRef;
    disabled: boolean;
    callbacks: WidgetActionCallbacks;
    targetEntityFormGroup: FormGroup;
    targetEntityMode: typeof LocationTargetEntityMode;
    attributeSources: LocationTargetSource[];
    attributeSourceTranslations: Map<LocationTargetSource, string>;
    AttributeScope: typeof AttributeScope;
    DataKeyType: typeof DataKeyType;
    filteredEntityAliasNames: Observable<string[]>;
    attributeSourceEntityFilter: EntityFilter;
    private entityAliases;
    private attributeSourceChange;
    private propagateChange;
    constructor(fb: FormBuilder, store: Store<AppState>, entityService: EntityService, destroyRef: DestroyRef);
    get isFromAttribute(): boolean;
    get aliasNameRequired(): boolean;
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: LocationTargetEntityConfig | undefined): void;
    validate(): ValidationErrors | null;
    clearAliasName(): void;
    private updateAttributeSourceEntityFilter;
    private attributeSourceFilter;
    private selectedAliasFilter;
    private queryableAliasFilter;
    private setAttributeSourceEntityFilter;
    private updateValidators;
    private targetEntityConfig;
    static ɵfac: i0.ɵɵFactoryDeclaration<LocationTargetEntityComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<LocationTargetEntityComponent, "tb-location-target-entity", never, { "disabled": { "alias": "disabled"; "required": false; }; "callbacks": { "alias": "callbacks"; "required": false; }; }, {}, never, never, false, never>;
}
