import { DestroyRef, ElementRef, EventEmitter, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import { MatStepper, StepperOrientation } from '@angular/material/stepper';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { PageComponent } from '@shared/components/page.component';
import { TranslateService } from '@ngx-translate/core';
import { AgentService } from '@core/http/agent.service';
import { EntityId } from '@shared/models/id/entity-id';
import { AgentApplication, AgentAppEvent, AgentAppProfile, AgentApplicationType, AgentAppTemplate, AgentInfo } from '@shared/models/agent.models';
import { StepBinding } from '@home/pages/agent/util/agent-app-step-inputs';
import { appProfileTrackKey } from '@home/pages/agent/util/virtual-app-profiles';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import { AgentAppWizardLoaderService } from '@home/pages/agent/wizard/agent-app-wizard-loader.service';
import { AgentAppWizardSubmitService } from '@home/pages/agent/wizard/agent-app-wizard-submit.service';
import { AgentAppUpgradeResult, AgentAppWizardFinish, AgentTypeCard } from '@home/pages/agent/wizard/agent-app-wizard.models';
import { EdgeTemplateCompatibilityService } from '@home/pages/agent/util/edge-template-compatibility.service';
import * as i0 from "@angular/core";
export declare class AgentAppInstallFlowComponent extends PageComponent implements OnInit {
    private router;
    private translate;
    private agentService;
    private loader;
    private submitSvc;
    private userPermissionsService;
    private fb;
    private dialog;
    private edgeTemplateCompatibility;
    private destroyRef;
    agentId: string;
    agent: AgentInfo;
    lockedType: AgentApplicationType | null;
    lockedRelatedEntity: EntityId | null;
    navigateToAgentOnFinish: boolean;
    selectAgent: boolean;
    embedded: boolean;
    showBack: boolean;
    stepperOrientation: Observable<StepperOrientation>;
    stepperLabelPosition: Observable<'bottom' | 'end'>;
    finished: EventEmitter<AgentAppWizardFinish>;
    cancelled: EventEmitter<AgentAppUpgradeResult>;
    back: EventEmitter<void>;
    managedApp: AgentApplication | null;
    managedAgent: AgentInfo | null;
    checkingManaged: boolean;
    installedApplication: AgentApplication | null;
    installedEvent: AgentAppEvent | null;
    stepper: MatStepper;
    bindings: StepBinding[];
    proposedYaml: string;
    currentYaml: string;
    diffSyncScroll: boolean;
    typeCards: AgentTypeCard[];
    selectedType: AgentApplicationType | null;
    template: AgentAppTemplate | null;
    composeType: string | null;
    composeTypeKeys: string[];
    loadingTemplate: boolean;
    loadError: string;
    private advanceAfterTypeSelect;
    appName: string;
    composeYaml: string;
    mergedApp: AgentApplication | null;
    submitting: boolean;
    useProfile: boolean;
    selectedProfile: AgentAppProfile | null;
    loadingProfiles: boolean;
    profileSelectFormGroup: UntypedFormGroup;
    filteredProfiles: Observable<AgentAppProfile[]>;
    readonly trackKey: typeof appProfileTrackKey;
    profileInput: ElementRef<HTMLInputElement>;
    private availableProfiles$;
    private availableProfilesValue;
    get helpLinkId(): string;
    get availableProfiles(): AgentAppProfile[];
    set availableProfiles(profiles: AgentAppProfile[]);
    credentialValues: Record<string, string>;
    relatedEntityId: EntityId | null;
    relatedEntityName: string | null;
    private savedProfile;
    private savedCustomCompose;
    private pendingCustomCompose;
    readonly canCreateAppProfile: boolean;
    constructor(router: Router, translate: TranslateService, agentService: AgentService, loader: AgentAppWizardLoaderService, submitSvc: AgentAppWizardSubmitService, userPermissionsService: UserPermissionsService, fb: UntypedFormBuilder, dialog: MatDialog, edgeTemplateCompatibility: EdgeTemplateCompatibilityService, destroyRef: DestroyRef);
    ngOnInit(): void;
    selectType(type: AgentApplicationType): void;
    private advanceFromTypeStep;
    toggleUseProfile(value: boolean): void;
    isVirtualProfile(profile: AgentAppProfile): boolean;
    profileTemplateLabel(profile: AgentAppProfile): string;
    private materializeAndSelect;
    private cacheRealProfiles;
    selectProfile(profile: AgentAppProfile): void;
    createProfile($event?: Event): void;
    openEditProfile(): void;
    get canHaveRelatedEntity(): boolean;
    get relatedEntityRequired(): boolean;
    onRelatedEntityChange(_entity: EntityId | null): void;
    onRelatedEntityName(name: string | null): void;
    private mergeWithRelatedEntity;
    private initCredentialValues;
    displayProfileFn(profile?: AgentAppProfile): string;
    clearProfile(): void;
    private clearProfileSelection;
    private loadProfilesForType;
    private loadTemplateForType;
    private applyTemplate;
    composeTypeLabel(composeType: string): string;
    onComposeTypeChange(composeType: string): void;
    private runMergeForPreview;
    private initBindings;
    private defaultAppName;
    onSelectedAgentChange(agent: AgentInfo | null): void;
    canProceedFromAgent(): boolean;
    canProceedFromType(): boolean;
    goToAgent(): void;
    goToAgentApplication(): void;
    goToAgentEvents(): void;
    private finishDeploy;
    canSubmit(): boolean;
    submit(): void;
    cancel(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppInstallFlowComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppInstallFlowComponent, "tb-agent-app-install-flow", never, { "agentId": { "alias": "agentId"; "required": false; }; "agent": { "alias": "agent"; "required": false; }; "lockedType": { "alias": "lockedType"; "required": false; }; "lockedRelatedEntity": { "alias": "lockedRelatedEntity"; "required": false; }; "navigateToAgentOnFinish": { "alias": "navigateToAgentOnFinish"; "required": false; }; "selectAgent": { "alias": "selectAgent"; "required": false; }; "embedded": { "alias": "embedded"; "required": false; }; "showBack": { "alias": "showBack"; "required": false; }; "stepperOrientation": { "alias": "stepperOrientation"; "required": false; }; "stepperLabelPosition": { "alias": "stepperLabelPosition"; "required": false; }; }, { "finished": "finished"; "cancelled": "cancelled"; "back": "back"; }, never, never, false, never>;
}
