import { EventEmitter, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { StepperOrientation } from '@angular/material/stepper';
import { Observable } from 'rxjs';
import { PageComponent } from '@shared/components/page.component';
import { TranslateService } from '@ngx-translate/core';
import { EntityId } from '@shared/models/id/entity-id';
import { AgentApplication, AgentAppProfile, AgentApplicationType, AgentAppTemplate, AgentInfo, AgentApplicationInfo } from '@shared/models/agent.models';
import { StepBinding } from '@home/pages/agent/util/agent-app-step-inputs';
import { AgentAppWizardLoaderService } from '@home/pages/agent/wizard/agent-app-wizard-loader.service';
import { AgentAppWizardSubmitService } from '@home/pages/agent/wizard/agent-app-wizard-submit.service';
import { AgentAppUpgradeResult, AgentAppWizardFinish } from '@home/pages/agent/wizard/agent-app-wizard.models';
import * as i0 from "@angular/core";
export declare class AgentAppUpdateFlowComponent extends PageComponent implements OnInit {
    private translate;
    private loader;
    private submitSvc;
    private dialog;
    agentId: string;
    agent: AgentInfo;
    existingApplication: AgentApplicationInfo;
    lockedRelatedEntity: EntityId | null;
    embedded: boolean;
    showBack: boolean;
    stepperOrientation: Observable<StepperOrientation>;
    stepperLabelPosition: Observable<'bottom' | 'end'>;
    finished: EventEmitter<AgentAppWizardFinish>;
    cancelled: EventEmitter<AgentAppUpgradeResult>;
    back: EventEmitter<void>;
    bindings: StepBinding[];
    proposedYaml: string;
    currentYaml: string;
    futureYaml: string;
    diffSyncScroll: boolean;
    readOnlyCompare: boolean;
    profileForCompare: AgentAppProfile | null;
    selectedType: AgentApplicationType | null;
    template: AgentAppTemplate | null;
    composeType: string | null;
    composeTypeKeys: string[];
    loadingTemplate: boolean;
    loadError: string;
    appName: string;
    composeYaml: string;
    mergedApp: AgentApplication | null;
    submitting: boolean;
    credentialValues: Record<string, string>;
    skipProfileRefetch: boolean;
    profileTemplateDrifted: boolean;
    relatedEntityId: EntityId | null;
    private initialRelatedEntityId;
    constructor(translate: TranslateService, loader: AgentAppWizardLoaderService, submitSvc: AgentAppWizardSubmitService, dialog: MatDialog);
    get isProfileManagedUpdate(): boolean;
    get canHaveRelatedEntity(): boolean;
    get relatedEntityShown(): boolean;
    get relatedEntityRequired(): boolean;
    ngOnInit(): void;
    private selectType;
    private loadTemplateForType;
    private applyTemplate;
    private runMergeForPreview;
    composeTypeLabel(composeType: string): string;
    onComposeTypeChange(composeType: string): void;
    private loadProfileForCompare;
    onRelatedEntityChange(): void;
    private refreshFutureCompare;
    openEditProfile(): void;
    private initCredentialValues;
    private initBindings;
    canSubmit(): boolean;
    submit(): void;
    cancel(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppUpdateFlowComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppUpdateFlowComponent, "tb-agent-app-update-flow", never, { "agentId": { "alias": "agentId"; "required": false; }; "agent": { "alias": "agent"; "required": false; }; "existingApplication": { "alias": "existingApplication"; "required": false; }; "lockedRelatedEntity": { "alias": "lockedRelatedEntity"; "required": false; }; "embedded": { "alias": "embedded"; "required": false; }; "showBack": { "alias": "showBack"; "required": false; }; "stepperOrientation": { "alias": "stepperOrientation"; "required": false; }; "stepperLabelPosition": { "alias": "stepperLabelPosition"; "required": false; }; }, { "finished": "finished"; "cancelled": "cancelled"; "back": "back"; }, never, never, false, never>;
}
