import { EventEmitter, OnInit } from '@angular/core';
import { MatStepper, StepperOrientation } from '@angular/material/stepper';
import { Observable } from 'rxjs';
import { PageComponent } from '@shared/components/page.component';
import { TranslateService } from '@ngx-translate/core';
import { AgentService } from '@core/http/agent.service';
import { EntityId } from '@shared/models/id/entity-id';
import { AgentApplication, AgentAppProfile, AgentApplicationType, AgentAppTemplate, AgentInfo, AgentApplicationInfo } from '@shared/models/agent.models';
import { StepBinding } from '@home/pages/agent/util/agent-app-step-inputs';
import { AgentAppWizardLoaderService } from '@home/pages/agent/wizard/agent-app-wizard-loader.service';
import { AgentAppWizardSubmitService } from '@home/pages/agent/wizard/agent-app-wizard-submit.service';
import { AgentAppUpgradeResult, AgentAppWizardFinish } from '@home/pages/agent/wizard/agent-app-wizard.models';
import * as i0 from "@angular/core";
export declare class AgentAppUpgradeFlowComponent extends PageComponent implements OnInit {
    private translate;
    private agentService;
    private loader;
    private submitSvc;
    agentId: string;
    agent: AgentInfo;
    existingApplication: AgentApplicationInfo;
    lockedRelatedEntity: EntityId | null;
    embedded: boolean;
    showBack: boolean;
    stepperOrientation: Observable<StepperOrientation>;
    stepperLabelPosition: Observable<'bottom' | 'end'>;
    finished: EventEmitter<AgentAppWizardFinish>;
    cancelled: EventEmitter<AgentAppUpgradeResult>;
    back: EventEmitter<void>;
    fromVersion: string | null;
    toVersion: string | null;
    profile: AgentAppProfile | null;
    mergedProfile: AgentAppProfile | null;
    profileProposedYaml: string;
    profileCurrentYaml: string;
    profileComposeYaml: string;
    private profileMergeRequested;
    loadingProfile: boolean;
    profileLoadError: string;
    profileUpgrading: boolean;
    profileUpgraded: boolean;
    showProfileUpgradeStep: boolean;
    stepper: MatStepper;
    bindings: StepBinding[];
    proposedYaml: string;
    currentYaml: string;
    composeType: string | null;
    diffSyncScroll: boolean;
    selectedType: AgentApplicationType | null;
    template: AgentAppTemplate | null;
    loadingTemplate: boolean;
    loadError: string;
    appName: string;
    composeYaml: string;
    mergedApp: AgentApplication | null;
    submitting: boolean;
    credentialValues: Record<string, string>;
    relatedEntityId: EntityId | null;
    constructor(translate: TranslateService, agentService: AgentService, loader: AgentAppWizardLoaderService, submitSvc: AgentAppWizardSubmitService);
    get isProfileBoundUpgrade(): boolean;
    get needsProfileUpgrade(): boolean;
    get canHaveRelatedEntity(): boolean;
    get relatedEntityShown(): boolean;
    get relatedEntityRequired(): boolean;
    ngOnInit(): void;
    private resolveUpgradeTemplate;
    private applyUpgradeTemplate;
    private runMergeForPreview;
    private resolveProfile;
    private maybeInitProfileDiff;
    canSubmitProfileUpgrade(): boolean;
    isProfileComposeYamlInvalid(): boolean;
    submitProfileUpgrade(): void;
    private failUpgradeLoad;
    private initBindings;
    get hasBackupVolumeInput(): boolean;
    get selectedBackupVolumeCount(): number;
    canSubmit(): boolean;
    submit(): void;
    cancel(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppUpgradeFlowComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppUpgradeFlowComponent, "tb-agent-app-upgrade-flow", never, { "agentId": { "alias": "agentId"; "required": false; }; "agent": { "alias": "agent"; "required": false; }; "existingApplication": { "alias": "existingApplication"; "required": false; }; "lockedRelatedEntity": { "alias": "lockedRelatedEntity"; "required": false; }; "embedded": { "alias": "embedded"; "required": false; }; "showBack": { "alias": "showBack"; "required": false; }; "stepperOrientation": { "alias": "stepperOrientation"; "required": false; }; "stepperLabelPosition": { "alias": "stepperLabelPosition"; "required": false; }; }, { "finished": "finished"; "cancelled": "cancelled"; "back": "back"; }, never, never, false, never>;
}
