import { EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { StepperOrientation } from '@angular/material/stepper';
import { BreakpointObserver } from '@angular/cdk/layout';
import { Observable } from 'rxjs';
import { EntityId } from '@shared/models/id/entity-id';
import { AgentApplication, AgentApplicationType, AgentInfo } from '@shared/models/agent.models';
import { AgentAppInstallWizardData, AgentAppInstallWizardResult, AgentAppUpgradeResult, AgentAppWizardFinish } from '@home/pages/agent/wizard/agent-app-wizard.models';
import * as i0 from "@angular/core";
export type { AgentAppInstallWizardData, AgentAppInstallWizardResult, AgentAppUpgradeResult } from '@home/pages/agent/wizard/agent-app-wizard.models';
export { isAgentAppUpgradeResult } from '@home/pages/agent/wizard/agent-app-wizard.models';
export declare class AgentAppInstallWizardComponent {
    private router;
    private dialog;
    private breakpointObserver;
    data: AgentAppInstallWizardData | null;
    dialogRef: MatDialogRef<AgentAppInstallWizardComponent, AgentAppInstallWizardResult> | null;
    agentId: string;
    agent: AgentInfo;
    mode: 'install' | 'update' | 'upgrade';
    application: AgentApplication | null;
    lockedType: AgentApplicationType | null;
    lockedRelatedEntity: EntityId | null;
    navigateToAgentOnFinish: boolean;
    selectAgent: boolean;
    embedded: boolean;
    showBack: boolean;
    finished: EventEmitter<AgentAppInstallWizardResult>;
    cancelled: EventEmitter<void>;
    stepperOrientation: Observable<StepperOrientation>;
    stepperLabelPosition: Observable<'bottom' | 'end'>;
    constructor(router: Router, dialog: MatDialog, breakpointObserver: BreakpointObserver, data: AgentAppInstallWizardData | null, dialogRef: MatDialogRef<AgentAppInstallWizardComponent, AgentAppInstallWizardResult> | null);
    onFinished(f: AgentAppWizardFinish): void;
    onCancelled(result: AgentAppUpgradeResult | null): void;
    onBack(): void;
    private closeOrEmit;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppInstallWizardComponent, [null, null, null, { optional: true; }, { optional: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppInstallWizardComponent, "tb-agent-app-install-wizard", never, { "agentId": { "alias": "agentId"; "required": false; }; "agent": { "alias": "agent"; "required": false; }; "mode": { "alias": "mode"; "required": false; }; "application": { "alias": "application"; "required": false; }; "lockedType": { "alias": "lockedType"; "required": false; }; "lockedRelatedEntity": { "alias": "lockedRelatedEntity"; "required": false; }; "navigateToAgentOnFinish": { "alias": "navigateToAgentOnFinish"; "required": false; }; "selectAgent": { "alias": "selectAgent"; "required": false; }; "embedded": { "alias": "embedded"; "required": false; }; "showBack": { "alias": "showBack"; "required": false; }; }, { "finished": "finished"; "cancelled": "cancelled"; }, never, never, false, never>;
}
