import { AfterViewInit, ChangeDetectorRef, EventEmitter, OnDestroy } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ControlValueAccessor } from '@angular/forms';
import { Subscription } from 'rxjs';
import { FlowConfig } from '@flowjs/ngx-flow';
import { DomSanitizer, SafeUrl } from '@angular/platform-browser';
import { UtilsService } from '@core/services/utils.service';
import { DialogService } from '@core/services/dialog.service';
import { TranslateService } from '@ngx-translate/core';
import { FileSizePipe } from '@shared/pipe/file-size.pipe';
import { ImagePipe } from '@shared/pipe/image.pipe';
import * as i0 from "@angular/core";
export declare class ImageInputComponent extends PageComponent implements AfterViewInit, OnDestroy, ControlValueAccessor {
    protected store: Store<AppState>;
    private utils;
    private sanitizer;
    private imagePipe;
    private dialog;
    private translate;
    private fileSize;
    private cd;
    accept: string;
    label: string;
    maxSizeByte: number;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    disabled: boolean;
    showClearButton: boolean;
    showPreview: boolean;
    inputId: string;
    allowedExtensions: string;
    processImageApiLink: boolean;
    resultAsFile: boolean;
    showFileName: boolean;
    fileName: string;
    fileNameChanged: EventEmitter<string>;
    imageUrl: string;
    file: File;
    safeImageUrl: SafeUrl;
    flow: FlowConfig;
    autoUploadSubscription: Subscription;
    private propagateChange;
    constructor(store: Store<AppState>, utils: UtilsService, sanitizer: DomSanitizer, imagePipe: ImagePipe, dialog: DialogService, translate: TranslateService, fileSize: FileSizePipe, cd: ChangeDetectorRef);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string): void;
    private updateModel;
    private filterFile;
    clearImage(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ImageInputComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ImageInputComponent, "tb-image-input", never, { "accept": { "alias": "accept"; "required": false; }; "label": { "alias": "label"; "required": false; }; "maxSizeByte": { "alias": "maxSizeByte"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "showClearButton": { "alias": "showClearButton"; "required": false; }; "showPreview": { "alias": "showPreview"; "required": false; }; "inputId": { "alias": "inputId"; "required": false; }; "allowedExtensions": { "alias": "allowedExtensions"; "required": false; }; "processImageApiLink": { "alias": "processImageApiLink"; "required": false; }; "resultAsFile": { "alias": "resultAsFile"; "required": false; }; "showFileName": { "alias": "showFileName"; "required": false; }; "fileName": { "alias": "fileName"; "required": false; }; }, { "fileNameChanged": "fileNameChanged"; }, never, never, false, never>;
}
