import { EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { EntityId } from '@shared/models/id/entity-id';
import { EntityType } from '@shared/models/entity-type.models';
import { EntityGroupInfo } from '@shared/models/entity-group.models';
import { ToggleHeaderOption } from '@shared/components/toggle-header.component';
import * as i0 from "@angular/core";
type OriginatorType = 'entity' | 'groupTenant' | 'ownerGroup';
export declare class OriginatorSelectComponent implements ControlValueAccessor, OnInit, OnDestroy {
    private store;
    translate: TranslateService;
    private fb;
    originatorFormGroup: UntypedFormGroup;
    modelValue: EntityId | null;
    allowedEntityTypes: Array<EntityType>;
    singleEntityText: string;
    groupOfEntitiesText: string;
    entitiesGroupOwnerText: string;
    headerOptions: ToggleHeaderOption[];
    required: boolean;
    disabled: boolean;
    currentGroupType: EventEmitter<EntityType>;
    currentUser: import("../public-api").AuthUser;
    private destroy$;
    private loadData;
    private propagateChange;
    constructor(store: Store<AppState>, translate: TranslateService, fb: UntypedFormBuilder);
    get originator(): OriginatorType;
    get isSingleEntityMode(): boolean;
    get isSingleAllowedEntityType(): boolean;
    get singleAllowedEntityType(): EntityType;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: EntityId | null): void;
    entityGroupLoaded(entityGroup: EntityGroupInfo): void;
    updateView(value: {
        originator: string;
        entityOriginatorId: EntityId;
        groupOriginatorId: EntityId;
    } | null): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<OriginatorSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<OriginatorSelectComponent, "tb-originator-select", never, { "allowedEntityTypes": { "alias": "allowedEntityTypes"; "required": false; }; "singleEntityText": { "alias": "singleEntityText"; "required": false; }; "groupOfEntitiesText": { "alias": "groupOfEntitiesText"; "required": false; }; "entitiesGroupOwnerText": { "alias": "entitiesGroupOwnerText"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; }, { "currentGroupType": "currentGroupType"; }, never, never, false, never>;
}
export {};
