import { EventEmitter } from '@angular/core';
import { Authority } from '@shared/models/authority.enum';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { AuthService } from '@core/auth/auth.service';
import { Router } from '@angular/router';
import * as i0 from "@angular/core";
export declare class UserMenuComponent {
    private store;
    private router;
    private authService;
    collapsed: boolean;
    menuClicked: EventEmitter<any>;
    authorities: typeof Authority;
    authority$: import("rxjs").Observable<Authority>;
    authorityName$: import("rxjs").Observable<string>;
    userDisplayName$: import("rxjs").Observable<string>;
    userFullName$: import("rxjs").Observable<string>;
    userInitials$: import("rxjs").Observable<string>;
    userEmail$: import("rxjs").Observable<string>;
    constructor(store: Store<AppState>, router: Router, authService: AuthService);
    private getAuthorityName;
    private getUserDisplayName;
    private getUserFullName;
    private getUserInitials;
    openAccount(): void;
    logout(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<UserMenuComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<UserMenuComponent, "tb-user-menu", never, { "collapsed": { "alias": "collapsed"; "required": false; }; }, { "menuClicked": "menuClicked"; }, never, never, false, never>;
}
