import { AfterViewInit, ChangeDetectorRef, ElementRef, OnDestroy } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityComponent } from '@home/components/entity/entity.component';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { EntityType } from '@shared/models/entity-type.models';
import { AgentAppProfile, AgentApplicationType } from '@shared/models/agent.models';
import { TranslateService } from '@ngx-translate/core';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { AgentService } from '@core/http/agent.service';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import * as i0 from "@angular/core";
export declare class AgentAppProfileComponent extends EntityComponent<AgentAppProfile> implements AfterViewInit, OnDestroy {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    protected entityValue: AgentAppProfile;
    protected entitiesTableConfigValue: EntityTableConfig<AgentAppProfile>;
    fb: UntypedFormBuilder;
    protected cd: ChangeDetectorRef;
    private agentService;
    private dialog;
    private dialogService;
    private hostElementRef;
    entityType: typeof EntityType;
    agentApplicationTypes: AgentApplicationType[];
    agentApplicationTypeTranslationMap: Map<AgentApplicationType, string>;
    templateVersion: string;
    nextVersion: string | null;
    private fullscreenHost;
    private composeEditor;
    private composeEditorSettingValue;
    private pendingComposeValue;
    set composeAceRef(ref: ElementRef<HTMLElement> | undefined);
    constructor(store: Store<AppState>, translate: TranslateService, entityValue: AgentAppProfile, entitiesTableConfigValue: EntityTableConfig<AgentAppProfile>, fb: UntypedFormBuilder, cd: ChangeDetectorRef, agentService: AgentService, dialog: MatDialog, dialogService: DialogService, hostElementRef: ElementRef<HTMLElement>);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    buildForm(entity: AgentAppProfile): UntypedFormGroup;
    updateForm(entity: AgentAppProfile): void;
    prepareFormValue(formValue: any): any;
    updateFormState(): void;
    canUpgrade(): boolean;
    onUpgrade($event: Event): void;
    private showAssignedAppsPropagationHint;
    onProfileIdCopied(): void;
    private loadTemplateVersion;
    private reloadEntity;
    private initComposeEditor;
    private pushComposeToEditor;
    private applyComposeEditorReadOnly;
    private extractArguments;
    private dumpCompose;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentAppProfileComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentAppProfileComponent, "tb-agent-app-profile", never, {}, {}, never, never, false, never>;
}
