import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { CellActionDescriptor, EntityColumn, EntityTableConfig, GroupActionDescriptor, HeaderActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { CustomerService } from '@core/http/customer.service';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import { AgentInfo } from '@shared/models/agent.models';
import { AgentService } from '@core/http/agent.service';
import { HomeDialogsService } from '@home/dialogs/home-dialogs.service';
import { AllEntitiesTableConfigService } from '@home/components/entity/all-entities-table-config.service';
import { AgentAutoProvisionDialogService } from '@home/components/agent/dialog/agent-auto-provision-dialog.service';
import * as i0 from "@angular/core";
export declare class AgentsTableConfigResolver {
    private allEntitiesTableConfigService;
    private store;
    private agentService;
    private customerService;
    private dialogService;
    private homeDialogs;
    private translate;
    private datePipe;
    private router;
    private dialog;
    private autoProvisionDialogService;
    private agentErrorEvents;
    constructor(allEntitiesTableConfigService: AllEntitiesTableConfigService<AgentInfo>, store: Store<AppState>, agentService: AgentService, customerService: CustomerService, dialogService: DialogService, homeDialogs: HomeDialogsService, translate: TranslateService, datePipe: DatePipe, router: Router, dialog: MatDialog, autoProvisionDialogService: AgentAutoProvisionDialogService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<AgentInfo>>;
    configDefaults(config: EntityTableConfig<AgentInfo>, route: ActivatedRouteSnapshot): void;
    configureColumns(config: EntityTableConfig<AgentInfo>): Array<EntityColumn<AgentInfo>>;
    private agentStatus;
    private agentStatusStyle;
    private hasAgentErrors;
    private agentErrorTooltip;
    private loadAgentErrorEvents;
    private goToAgentErrorEvents;
    private reconcileAgentErrorEvents;
    configureEntityFunctions(config: EntityTableConfig<AgentInfo>): void;
    configureCellActions(config: EntityTableConfig<AgentInfo>): Array<CellActionDescriptor<AgentInfo>>;
    private canUpgrade;
    private openUpgrade;
    private manageApplications;
    private openAgent;
    configureGroupActions(): Array<GroupActionDescriptor<AgentInfo>>;
    configureAddActions(config: EntityTableConfig<AgentInfo>): Array<HeaderActionDescriptor>;
    private autoProvisionAgent;
    private addAgent;
    openInstallInstructions($event: Event, agent: AgentInfo, afterAdd?: boolean, config?: EntityTableConfig<AgentInfo>): void;
    manageOwnerAndGroups($event: Event, agent: AgentInfo, config: EntityTableConfig<AgentInfo>): void;
    onAgentAction(action: EntityAction<AgentInfo>, config: EntityTableConfig<AgentInfo>): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentsTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<AgentsTableConfigResolver>;
}
