import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { Observable } from 'rxjs';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import { AgentApplicationInfo } from '@shared/models/agent.models';
import { AgentService } from '@core/http/agent.service';
import * as i0 from "@angular/core";
export declare class AgentApplicationsTableConfigResolver {
    private agentService;
    private translate;
    private datePipe;
    private router;
    private dialog;
    private dialogService;
    private readonly config;
    private agentId;
    private agent;
    private templateCache;
    constructor(agentService: AgentService, translate: TranslateService, datePipe: DatePipe, router: Router, dialog: MatDialog, dialogService: DialogService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<AgentApplicationInfo>>;
    private applyRelatedEntityChange;
    private configureColumns;
    private readonly statusCellStyle;
    private readonly statusHeaderStyle;
    private statusIcon;
    private profileTemplateDrifted;
    private profileSyncBadge;
    private profileSyncTooltip;
    private originBadge;
    private appTypeBadge;
    private templateCell;
    private enrichWithTemplates;
    private configureCellActions;
    private update;
    private restart;
    private openDeleteDialog;
    private showDeleteDialog;
    private openUpgradeWizard;
    private showUpgradeWizard;
    private openInstallWizard;
    private showUpdateHintDialog;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentApplicationsTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<AgentApplicationsTableConfigResolver>;
}
