import { ElementRef, EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { TruncatePipe } from '@shared/pipe/truncate.pipe';
import { MatDialog } from '@angular/material/dialog';
import { MatAutocomplete } from '@angular/material/autocomplete';
import { AgentProfileId } from '@shared/models/id/agent-profile-id';
import { AgentProfile, AgentProfileInfo } from '@shared/models/agent.models';
import { AgentService } from '@core/http/agent.service';
import { MatFormFieldAppearance, SubscriptSizing } from '@angular/material/form-field';
import { Operation, Resource } from '@shared/models/security.models';
import * as i0 from "@angular/core";
export declare class AgentProfileAutocompleteComponent implements ControlValueAccessor, OnInit {
    private store;
    translate: TranslateService;
    truncate: TruncatePipe;
    private agentService;
    private fb;
    private dialog;
    resource: typeof Resource;
    operation: typeof Operation;
    selectAgentProfileFormGroup: UntypedFormGroup;
    modelValue: AgentProfileId | null;
    subscriptSizing: SubscriptSizing;
    selectDefaultProfile: boolean;
    editProfileEnabled: boolean;
    addNewProfile: boolean;
    required: boolean;
    disabled: boolean;
    hint: string;
    appearance: MatFormFieldAppearance;
    showDetailsPageLink: boolean;
    get agentProfileURL(): string | null;
    agentProfileUpdated: EventEmitter<AgentProfileId>;
    agentProfileChanged: EventEmitter<AgentProfileInfo>;
    agentProfileInput: ElementRef;
    agentProfileAutocomplete: MatAutocomplete;
    filteredAgentProfiles: Observable<Array<AgentProfileInfo>>;
    searchText: string;
    private dirty;
    private propagateChange;
    constructor(store: Store<AppState>, translate: TranslateService, truncate: TruncatePipe, agentService: AgentService, fb: UntypedFormBuilder, dialog: MatDialog);
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    ngOnInit(): void;
    selectDefaultAgentProfileIfNeeded(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: AgentProfileId | null): void;
    onFocus(): void;
    updateView(agentProfile: AgentProfileInfo | null): void;
    displayAgentProfileFn(profile?: AgentProfileInfo): string | undefined;
    fetchAgentProfiles(searchText?: string): Observable<Array<AgentProfileInfo>>;
    clear(): void;
    textIsNotEmpty(text: string): boolean;
    agentProfileEnter($event: KeyboardEvent): void;
    createAgentProfile($event: Event, profileName: string): void;
    editAgentProfile($event: Event): void;
    openAgentProfileDialog(agentProfile: AgentProfile, isAdd: boolean): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentProfileAutocompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentProfileAutocompleteComponent, "tb-agent-profile-autocomplete", never, { "subscriptSizing": { "alias": "subscriptSizing"; "required": false; }; "selectDefaultProfile": { "alias": "selectDefaultProfile"; "required": false; }; "editProfileEnabled": { "alias": "editProfileEnabled"; "required": false; }; "addNewProfile": { "alias": "addNewProfile"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "hint": { "alias": "hint"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; "showDetailsPageLink": { "alias": "showDetailsPageLink"; "required": false; }; }, { "agentProfileUpdated": "agentProfileUpdated"; "agentProfileChanged": "agentProfileChanged"; }, never, never, false, never>;
}
