import { AfterViewInit, ChangeDetectorRef, DestroyRef, ElementRef, OnDestroy } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityComponent } from '@home/components/entity/entity.component';
import { UntypedFormBuilder, UntypedFormControl, UntypedFormGroup } from '@angular/forms';
import { EntityType } from '@shared/models/entity-type.models';
import { AgentApplicationSaveRequest, AgentAppProfileInfo, AgentApplicationInfo, AgentApplicationType } from '@shared/models/agent.models';
import { TranslateService } from '@ngx-translate/core';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { AgentService } from '@core/http/agent.service';
import { DialogService } from '@core/services/dialog.service';
import { MatDialog } from '@angular/material/dialog';
import { Router } from '@angular/router';
import { EntityService } from '@core/http/entity.service';
import { Observable } from 'rxjs';
import * as i0 from "@angular/core";
export declare class AgentApplicationComponent extends EntityComponent<AgentApplicationInfo> implements AfterViewInit, OnDestroy {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    protected entityValue: AgentApplicationInfo;
    protected entitiesTableConfigValue: EntityTableConfig<AgentApplicationInfo>;
    fb: UntypedFormBuilder;
    protected cd: ChangeDetectorRef;
    private agentService;
    private entityService;
    private dialogService;
    private dialog;
    private router;
    private destroyRef;
    private hostElementRef;
    entityType: typeof EntityType;
    private fullscreenHost;
    agentApplicationTypes: AgentApplicationType[];
    agentApplicationTypeTranslationMap: Map<AgentApplicationType, string>;
    agentApplicationOriginTranslationMap: Map<import("@shared/models/agent.models").AgentApplicationOrigin, string>;
    templateVersion: string;
    relatedEntity: {
        name: string;
        url: string;
        typeLabel: string;
    } | null;
    profileSearchCtrl: UntypedFormControl;
    filteredProfiles: Observable<AgentAppProfileInfo[]>;
    private availableProfiles$;
    private availableProfilesValue;
    get availableProfiles(): AgentAppProfileInfo[];
    set availableProfiles(profiles: AgentAppProfileInfo[]);
    private detachedComposeYaml;
    private detachedArguments;
    private composeEditor;
    private composeEditorSettingValue;
    private pendingComposeValue;
    set composeAceRef(ref: ElementRef<HTMLElement> | undefined);
    constructor(store: Store<AppState>, translate: TranslateService, entityValue: AgentApplicationInfo, entitiesTableConfigValue: EntityTableConfig<AgentApplicationInfo>, fb: UntypedFormBuilder, cd: ChangeDetectorRef, agentService: AgentService, entityService: EntityService, dialogService: DialogService, dialog: MatDialog, router: Router, destroyRef: DestroyRef, hostElementRef: ElementRef<HTMLElement>);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    updateFormState(): void;
    private initComposeEditor;
    private pushComposeToEditor;
    private applyComposeEditorReadOnly;
    get isProfileManaged(): boolean;
    get selectedProfileId(): string | null;
    displayProfileFn(profile?: AgentAppProfileInfo): string;
    clearProfileField(): void;
    syncProfileDisplay(): void;
    onProfileChange(profileId: string | null): void;
    private resolveProfile;
    private confirmProfileAssignment;
    private confirmComposeCompare;
    private applyProfileSelection;
    private applyProfileConfig;
    private loadProfilesForType;
    hideDelete(): boolean;
    canUpgrade(): boolean;
    get profileTemplateDrifted(): boolean;
    canHaveRelatedEntity(): boolean;
    buildForm(entity: AgentApplicationInfo): UntypedFormGroup;
    updateForm(entity: AgentApplicationInfo): void;
    private resolveRelatedEntity;
    get selectedProfileName(): string;
    prepareFormValue(formValue: any): AgentApplicationSaveRequest;
    onUpdate($event: Event): void;
    onRestart($event: Event): void;
    onUpgrade($event: Event): void;
    onDelete($event: Event): void;
    onAppIdCopied(): void;
    private reloadEntity;
    private extractArguments;
    private dumpCompose;
    static ɵfac: i0.ɵɵFactoryDeclaration<AgentApplicationComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AgentApplicationComponent, "tb-agent-application", never, {}, {}, never, never, false, never>;
}
